# 用基础镜像地址替换下方镜像地址
FROM reg.docker.alibaba-inc.com/aone-base/baseimage:tag

# 指定运行时的系统环境变量,如下请替换appName为自己应用名称
ENV APP_NAME appName

# 健康检查默认3秒钟做一次,默认做100次也就是300秒,这里设置最多等180秒
ENV ali_start_timeout=180

#防止6u在7u宿主机上运行挂起不动
# RUN sed -i '/console output/ d' /etc/init/rcS.conf


# 将应用nginx配置文件复制到镜像中
COPY environment/testing/cai/bin/* /home/admin/cai/bin/
COPY environment/testing/cai/conf/* /home/admin/cai/conf/

# 将构建出的主包复制到指定镜像目录中（替换自己的压缩包名）
COPY $APP_NAME.tgz /home/admin/$APP_NAME/target/
ENV env testing
