# 当前文件将不常变化的内容用于构建一个基础镜像，以便在不同环境的dockerfile中引用
FROM reg.docker.alibaba-inc.com/alibase/alios7u2-min:1.13

# 指定运行时的系统环境变量,如下请替换appName为自己应用名称
ENV APP_NAME appName

# 构建时要做的事，一般是执行shell命令，例如用来安装必要软件，创建文件（夹），修改文件
RUN yum install tengine-proxy -b current -y;\
    mkdir -p /home/admin/${APP_NAME}/target/

# 这里用RUN 指令安装你的不常变化的rpm包
#RUN rpm  -Uvh http://xxxx (可以在 http://rpm.alibaba-inc.com 上搜索包获得下载地址) 

# 将应用启动脚本、健康检查脚本复制到镜像中
COPY environment/common/bin/ /home/admin/$APP_NAME/bin/
COPY environment/common/cai/ /home/admin/cai/
COPY environment/common/app.service.tmpl /home/admin/app.service.tmpl

#下面是应用起停脚本和健康检查, 设置文件操作权限
RUN echo "/home/admin/$APP_NAME/bin/appctl.sh stop" > /home/admin/stop.sh && \
    echo "/home/admin/$APP_NAME/bin/appctl.sh restart" >> /home/admin/start.sh && \
    echo "/home/admin/$APP_NAME/bin/preload.sh" > /home/admin/health.sh && \
    chmod +x /home/admin/*.sh && \
    chmod -R a+x /home/admin/$APP_NAME/bin/ 

# 挂载数据卷,指定目录挂载到宿主机上面,为了能够保存（持久化）数据以及共享容器间的数据，为了实现数据共享，例如日志文件共享到宿主机或容器间共享数据.
VOLUME /home/admin/logs \
    /home/admin/$APP_NAME/logs \
    /home/admin/cai/logs

# 启动容器时进入的工作目录
WORKDIR /home/admin/$APP_NAME/

# 定义应用启动用户名
USER admin

#容器启动时自动执行的脚本，我们一般会将应用启动脚本放在这里，相当于系统自启应用
ENTRYPOINT ["/home/admin/start.sh"]
