// Verbatim declarations copied from github.com/DingTalk-Real-AI/dingtalk-workspace-cli
// tag v1.0.62-beta.8 (Apache-2.0; see clicompat/NOTICE). Generated by
// clicompat_excerpts.py: each declaration, doc comment included, is byte for
// byte the dws source at the file and line listed; nothing else is in this
// file except the package clause and imports.
//
//	const ExitSuccess                            internal/helpers/errors.go:12
//	const CodeAuthNotConfigured                  internal/helpers/errors.go:21
//	type CLIError                                internal/helpers/errors.go:48
//	method CLIError.Error                        internal/helpers/errors.go:56
//	method CLIError.Unwrap                       internal/helpers/errors.go:67
//	method CLIError.ExitCode                     internal/helpers/errors.go:69
//	func suggestForBusinessErrorText             internal/helpers/errors.go:411
//	const genericPermissionSuggestion            internal/helpers/errors.go:477
//	func permissionDeniedSuggestion              internal/helpers/errors.go:483
//	func documentPermissionErrorText             internal/helpers/errors.go:453
//	const permissionApplySteps                   internal/helpers/errors.go:561
//	const permissionApplyGuidance                internal/helpers/errors.go:565
//	func isBusinessError                         internal/helpers/helpers.go:793
//	func isErrorCodeValue                        internal/helpers/helpers.go:831
//	func isNotLoggedInError                      internal/helpers/helpers.go:858
//	var dwsGatewayErrors                         internal/helpers/helpers.go:890
//	func getDWSGatewayErrorCode                  internal/helpers/helpers.go:905
//	func suggestForBusinessError                 internal/helpers/helpers.go:916
//	func businessErrorMessage                    internal/helpers/helpers.go:922
//	func businessErrorDisplayMessage             internal/helpers/helpers.go:934
//	func normalizeA2UIUpdateFlowStatus           internal/helpers/chat.go:35
//	func parseA2UIMessages                       internal/helpers/chat.go:60
//	func parseA2UIAnnotations                    internal/helpers/chat.go:74
//	func applyProjectedChatPagination            internal/helpers/chat.go:205
//	func withProjectedChatOperation              internal/helpers/chat.go:261
//	func projectChatMessagesPayloadWithLedger    internal/helpers/chat.go:334
//	func chatDecryptFailure                      internal/helpers/chat.go:473
//	func firstChatMapValue                       internal/helpers/chat.go:485
//	func firstNonEmptyLiteral                    internal/helpers/chat.go:494
//	func projectExistingChatMessageCollections   internal/helpers/chat.go:503
//	func projectChatConversationMessageGroups    internal/helpers/chat.go:528
//	func projectChatMessageItems                 internal/helpers/chat.go:554
//	func chatMessageMapItems                     internal/helpers/chat.go:566
//	func projectChatMessageItem                  internal/helpers/chat.go:585 (modified, see below)
//	func defaultChatMessageListTime              internal/helpers/chat.go:1462
//	func sanitizeTitleFromText                   internal/helpers/chat.go:2057
//	func truncateTitleToBytes                    internal/helpers/chat.go:2093
//	func marshalJSONRaw                          internal/helpers/chat.go:2111
//	func normalizeAtPlaceholders                 internal/helpers/chat.go:2223
//	func NormalizeMessageMentions                internal/helpers/chat.go:2249
//	func applyCurrentUserGroupMentions           internal/helpers/chat.go:2266
//	func addMissingCurrentUserMentionPlaceholders internal/helpers/chat.go:2284
//	func containsMessageMention                  internal/helpers/chat.go:2308
//	func cloneStringAnyMap                       internal/helpers/chat.go:3174
//	func unmarshalJSONUseNumber                  internal/helpers/chat.go:3182
//	func ParseChatA2UIMessages                   internal/helpers/chat_shortcut_bridge.go:17
//	func PrepareChatReplyMentions                internal/helpers/chat_shortcut_bridge.go:21
//	func parseCSVValues                          internal/helpers/contact.go:22
//	func cleanStringValues                       internal/helpers/contact.go:38
//	var agoalLoadLocation                        internal/helpers/agoal.go:11
//	func shanghaiLocation                        internal/helpers/agoal.go:630
//
// internal/helpers is not vendored (its files import cobra and most of dws).
//
// Modification: projectChatMessageItem starts with the complexity guard of
// budget.go (not in dws), which dws-for-tag adds because it projects in the
// host process where dws projected in a killable subprocess.

package clicompat

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/multica-ai/multica/server/pkg/dws/clicompat/chatmsg"
)

const (
	ExitSuccess    = 0
	ExitAPI        = 1
	ExitAuth       = 2
	ExitValidation = 3
	ExitPermission = 4
	ExitInternal   = 5
)

const (
	CodeAuthNotConfigured  = "AUTH_NOT_CONFIGURED"
	CodeAuthTokenExpired   = "AUTH_TOKEN_EXPIRED"
	CodeAuthPermission     = "AUTH_PERMISSION_DENIED"
	CodeNetworkTimeout     = "NETWORK_TIMEOUT"
	CodeNetworkUnreachable = "NETWORK_UNREACHABLE"
	CodeLockTimeout        = "LOCK_TIMEOUT"
	CodeResourceNotFound   = "RESOURCE_NOT_FOUND"
	CodeTableNotFound      = "TABLE_NOT_FOUND"
	CodeSheetNotFound      = "SHEET_NOT_FOUND"
	CodeFieldNotFound      = "FIELD_NOT_FOUND"
	CodeRecordNotFound     = "RECORD_NOT_FOUND"
	CodeInvalidJSON        = "INPUT_INVALID_JSON"
	CodeInvalidPath        = "INPUT_INVALID_PATH"
	CodeInputTooLarge      = "INPUT_TOO_LARGE"
	CodeMissingParam       = "INPUT_MISSING_PARAM"
	CodeInvalidParam       = "INPUT_INVALID_PARAM"
	CodeFileNotFound       = "INPUT_FILE_NOT_FOUND"
	CodeFileAlreadyExists  = "INPUT_FILE_ALREADY_EXISTS"
	CodeContentTruncated   = "CONTENT_TRUNCATED"
	CodeMCPServerError     = "MCP_SERVER_ERROR"
	CodeMCPToolError       = "MCP_TOOL_ERROR"
	CodeUnclassified       = "UNCLASSIFIED"
)

// CLIError is a user-friendly error with code, suggestion, and exit code.
// Supports traceability via the Operation field and error chain via Cause.
type CLIError struct {
	Code       string
	Message    string
	Suggestion string
	Operation  string // the operation that failed (for traceability)
	Cause      error
}

func (e *CLIError) Error() string {
	s := fmt.Sprintf("[%s] %s", e.Code, e.Message)
	if e.Operation != "" {
		s += fmt.Sprintf(" (operation: %s)", e.Operation)
	}
	if e.Suggestion != "" {
		s += fmt.Sprintf("\n  hint: %s", e.Suggestion)
	}
	return s
}

func (e *CLIError) Unwrap() error { return e.Cause }

func (e *CLIError) ExitCode() int {
	switch e.Code {
	case CodeAuthNotConfigured, CodeAuthTokenExpired:
		return ExitAuth
	case CodeAuthPermission:
		return ExitPermission
	case CodeMissingParam, CodeInvalidParam, CodeInvalidJSON, CodeInvalidPath, CodeInputTooLarge, CodeFileNotFound, CodeFileAlreadyExists:
		return ExitValidation
	case CodeContentTruncated:
		return ExitAPI
	case CodeMCPServerError, CodeMCPToolError:
		return ExitAPI
	case CodeNetworkTimeout, CodeNetworkUnreachable:
		return ExitAPI
	case CodeResourceNotFound, CodeTableNotFound, CodeSheetNotFound, CodeFieldNotFound, CodeRecordNotFound:
		return ExitAPI
	case CodeLockTimeout, CodeUnclassified:
		return ExitInternal
	default:
		return ExitInternal
	}
}

// suggestForBusinessErrorText returns a user-facing suggestion for known business
// error text patterns, or "" if no specific suggestion applies.
func suggestForBusinessErrorText(text string) string {
	switch {
	case strings.Contains(text, "搜索内容不能为空"):
		return "请提供非空搜索关键词: dws doc search --query \"关键词\"\n  若需浏览最近文档: dws doc list"
	case strings.Contains(text, "User has no permission to access this email"):
		return "请确认邮箱地址正确，查看可用邮箱: dws mail mailbox list"
	case strings.Contains(text, "频率超限") || strings.Contains(text, "rate limit"):
		return "API rate limit exceeded, wait a moment and retry"
	case strings.Contains(text, "用户不存在") || strings.Contains(text, "不属于当前组织") ||
		strings.Contains(text, "成员不存在"):
		return "请检查用户 ID 或组织信息是否正确，跨组织用户需通过 --members 格式携带 corpId"
	case strings.Contains(text, "未找到指定工具") || strings.Contains(text, "MCP不存在"):
		return "后端工具未注册或已下线；这不是参数格式问题。请升级到包含该工具注册的后端/静态端点版本，或改用当前可用替代命令。"
	case strings.Contains(text, "参数错误") || strings.Contains(text, "param error"):
		return "Check input parameters. Use --help for available flags"
	case strings.Contains(text, "无权限访问") || strings.Contains(text, "没有访问权限") ||
		strings.Contains(text, "没有权限") || strings.Contains(text, "权限不足") ||
		strings.Contains(text, "no permission") || strings.Contains(text, "permission denied") ||
		strings.Contains(text, "FORBIDDEN"):
		return permissionDeniedSuggestion(text)
	default:
		return ""
	}
}

// genericPermissionSuggestion is the product-neutral suggestion for
// permission-denied errors that are not specific to document/wiki access.
const genericPermissionSuggestion = "Verify your account has permission for this resource"

// permissionDeniedSuggestion picks between document apply-permission guidance
// and a product-neutral hint: only document/wiki-specific errors point at
// dws drive permission apply-*, so other products never get a misleading
// document-permission suggestion.
func permissionDeniedSuggestion(text string) string {
	if documentPermissionErrorText(text) {
		return permissionApplyGuidance
	}
	return genericPermissionSuggestion
}

// documentPermissionErrorText reports whether a permission-denied message is
// specific to document/wiki permission (drive/doc/wiki), e.g. the role
// threshold wording emitted by the member-management APIs or the document
// permission error codes embedded in the message text.
func documentPermissionErrorText(text string) bool {
	if text == "" {
		return false
	}
	lower := strings.ToLower(text)
	return strings.Contains(lower, "forbidden.no.auth") ||
		strings.Contains(lower, "forbidden.accessdenied") ||
		strings.Contains(text, "需要您具备") || strings.Contains(text, "及以上角色")
}

// permissionApplySteps lists the two-step commands to apply for document access.
const permissionApplySteps = "  1) 查可申请角色与审批人: dws drive permission apply-info --node <节点ID或URL>\n" +
	"  2) 选定角色与审批人后发起申请: dws drive permission apply --node <节点ID或URL> --role <EDITOR|DOWNLOADER|READER> --users <审批人userId>"

// permissionApplyGuidance is the standard suggestion for permission-denied errors.
const permissionApplyGuidance = "若你对该文档/知识库暂无访问权限，可发起权限申请:\n" + permissionApplySteps

// isBusinessError checks if a parsed JSON body represents a business-level error.
func isBusinessError(body map[string]any) bool {
	if v, ok := body["error"]; ok {
		switch t := v.(type) {
		case string:
			if strings.TrimSpace(t) != "" {
				return true
			}
		case map[string]any:
			if len(t) > 0 {
				return true
			}
		case []any:
			if len(t) > 0 {
				return true
			}
		default:
			if t != nil {
				return true
			}
		}
	}
	if v, ok := body["status"].(string); ok && strings.EqualFold(strings.TrimSpace(v), "error") {
		return true
	}
	for _, key := range []string{"errorCode", "error_code", "errcode", "err_code", "code"} {
		if isErrorCodeValue(body[key]) {
			return true
		}
	}
	if v, ok := body["success"].(bool); ok && !v {
		return true
	}
	if v, ok := body["success"].(string); ok && strings.EqualFold(v, "false") {
		return true
	}
	return false
}

func isErrorCodeValue(v any) bool {
	switch t := v.(type) {
	case string:
		code := strings.TrimSpace(t)
		if code == "" {
			return false
		}
		switch strings.ToLower(code) {
		case "0", "ok", "success", "succeed":
			return false
		default:
			return true
		}
	case float64:
		return t != 0
	case int:
		return t != 0
	case int64:
		return t != 0
	case json.Number:
		return strings.TrimSpace(t.String()) != "" && t.String() != "0"
	default:
		return false
	}
}

// isNotLoggedInError checks if the error body indicates missing authentication.
func isNotLoggedInError(body map[string]any) bool {
	if errMsg, ok := body["error"].(string); ok {
		if strings.Contains(errMsg, "Missing service_id or access_key") {
			return true
		}
	}
	return false
}

// dwsGatewayErrors is the set of DWS gateway-level auth error codes that
// must be surfaced as CodeAuthTokenExpired so the runner / overlay knows the
// current bearer token has been rejected.
//
// TOKEN_VERIFIED_FAILED / USER_TOKEN_ILLEGAL come from upstream DingTalk
// services that pass through the gateway; they are server-side rejections
// of an otherwise locally-valid token.
var dwsGatewayErrors = map[string]bool{
	"DWS_SERVICE_UNAUTHORIZED": true,
	"DWS_AUTH_SERVICE_FAILED":  true,
	"TOKEN_VERIFIED_FAILED":    true,
	"USER_TOKEN_ILLEGAL":       true,
}

// getDWSGatewayErrorCode extracts a DWS gateway error code from errBody.
//
// Field-name coverage: the gateway and upstream services are inconsistent
// about which key carries the code — we have observed all of "errorCode",
// "error_code" and "code" in the wild — so check all three. The transport
// layer's ExtractServerDiagnosticsFromMap normalises into ServerErrorCode,
// but ClassifyToolResultContent is fed the raw content map and must do its
// own lookup.
func getDWSGatewayErrorCode(errBody map[string]any) (string, bool) {
	for _, key := range []string{"errorCode", "error_code", "code"} {
		if code, ok := errBody[key].(string); ok && dwsGatewayErrors[code] {
			return code, true
		}
	}
	return "", false
}

// suggestForBusinessError returns a user-facing suggestion for known business
// error patterns in a parsed JSON body, or "" if no specific suggestion applies.
func suggestForBusinessError(body map[string]any) string {
	return suggestForBusinessErrorText(businessErrorMessage(body))
}

// businessErrorMessage extracts the human-readable message from a parsed error
// body, checking errorMsg > errorMessage > message > error. Returns "" if none present.
func businessErrorMessage(body map[string]any) string {
	for _, k := range []string{"errorMsg", "errorMessage", "message", "error"} {
		if v, ok := body[k].(string); ok && v != "" {
			return v
		}
	}
	return ""
}

// businessErrorDisplayMessage extracts the human-readable message from a parsed
// error body, appends the backend error code and logId if present (for
// traceability), and falls back to rawText if no message field is found.
func businessErrorDisplayMessage(body map[string]any, rawText string) string {
	msg := businessErrorMessage(body)
	if msg == "" {
		return rawText
	}
	var extras []string
	for _, k := range []string{"errorCode", "error_code", "code"} {
		if code, ok := body[k].(string); ok && code != "" && !strings.Contains(msg, code) {
			extras = append(extras, "code: "+code)
			break
		}
	}
	if logId, ok := body["logId"].(string); ok && logId != "" && !strings.Contains(msg, logId) {
		extras = append(extras, "logId: "+logId)
	}
	if len(extras) > 0 {
		msg = msg + " (" + strings.Join(extras, ", ") + ")"
	}
	return msg
}

func normalizeA2UIUpdateFlowStatus(raw string) (string, error) {
	switch strings.ToUpper(strings.TrimSpace(raw)) {
	case "1", "PROCESSING":
		return "PROCESSING", nil
	case "2", "INPUTTING":
		return "INPUTTING", nil
	case "3", "FINISH":
		return "FINISH", nil
	case "4", "EXECUTING":
		return "EXECUTING", nil
	case "5", "ERROR":
		return "ERROR", nil
	case "6", "ABORTED":
		return "ABORTED", nil
	case "7", "TIMEOUT":
		return "TIMEOUT", nil
	case "8", "CONFIRMING":
		return "CONFIRMING", nil
	case "9", "CONFIRMED":
		return "CONFIRMED", nil
	default:
		return "", fmt.Errorf("--flow-status must be one of PROCESSING, INPUTTING, FINISH, EXECUTING, ERROR, ABORTED, TIMEOUT, CONFIRMING, CONFIRMED")
	}
}

func parseA2UIMessages(raw string) ([]string, error) {
	if strings.TrimSpace(raw) == "" {
		return nil, fmt.Errorf("--content is required")
	}
	var messages []string
	if err := json.Unmarshal([]byte(raw), &messages); err != nil {
		return nil, fmt.Errorf("--content must be a JSON string array")
	}
	if len(messages) == 0 {
		return nil, fmt.Errorf("--content must contain at least one message")
	}
	return messages, nil
}

func parseA2UIAnnotations(raw string) ([]map[string]json.RawMessage, error) {
	var annotations []map[string]json.RawMessage
	if err := json.Unmarshal([]byte(raw), &annotations); err != nil || annotations == nil {
		return nil, fmt.Errorf("--a2ui-annotations must be a JSON object array")
	}
	for _, annotation := range annotations {
		if annotation == nil {
			return nil, fmt.Errorf("--a2ui-annotations must contain only JSON objects")
		}
	}
	return annotations, nil
}

func applyProjectedChatPagination(payload, source map[string]any, paginationDirection string) {
	if paginationDirection == "" {
		return
	}
	messages, _ := payload["messages"].([]map[string]any)
	preserved := make(map[string]any)
	for _, key := range []string{"count", "enrichedCount", "failedCount", "failures", "partial", "truncated"} {
		if value, exists := payload[key]; exists {
			preserved[key] = value
		}
	}
	for key, value := range chatmsg.NewMessageListPayload(messages) {
		if _, exists := payload[key]; !exists {
			payload[key] = value
		}
	}
	delete(payload, "nextPage")
	chatmsg.ApplyMessagePagination(payload, source, messages, paginationDirection)
	for key, value := range preserved {
		payload[key] = value
	}
	if payload["complete"] == true {
		payload["stopReason"] = "source_complete"
	} else {
		payload["stopReason"] = "single_page"
	}
}

func withProjectedChatOperation(operation string, err error) error {
	var cliErr *CLIError
	if errors.As(err, &cliErr) && cliErr.Operation == "" {
		withOperation := *cliErr
		withOperation.Operation = operation
		return &withOperation
	}
	return err
}

func projectChatMessagesPayloadWithLedger(data map[string]any, search bool, ledger map[string]any) map[string]any {
	payload := projectExistingChatMessageCollections(data)
	items := chatmsg.ListMessageItems(payload)
	if search {
		items = chatmsg.SearchItems(payload)
	}
	messages := make([]map[string]any, 0, len(items))
	for _, item := range items {
		messages = append(messages, projectChatMessageItem(item, nil))
	}

	payload["messages"] = messages
	if result, ok := payload["result"].(map[string]any); ok {
		if _, exists := result["messages"]; exists {
			projectedResult := make(map[string]any, len(result))
			for key, value := range result {
				projectedResult[key] = value
			}
			projectedResult["messages"] = messages
			payload["result"] = projectedResult
		}
	}
	for key, value := range ledger {
		payload[key] = value
	}
	return payload
}

func chatDecryptFailure(messageID, conversationID, reason string) map[string]any {
	failure := map[string]any{
		"stage":     "message-decrypt",
		"messageId": strings.TrimSpace(messageID),
		"reason":    firstNonEmptyLiteral(reason, "decrypt_failed"),
	}
	if strings.TrimSpace(conversationID) != "" {
		failure["conversationId"] = strings.TrimSpace(conversationID)
	}
	return failure
}

func firstChatMapValue(message map[string]any, keys ...string) any {
	for _, key := range keys {
		if value, ok := message[key]; ok {
			return value
		}
	}
	return nil
}

func firstNonEmptyLiteral(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func projectExistingChatMessageCollections(data map[string]any) map[string]any {
	payload := cloneStringAnyMap(data)
	if messages, exists := payload["messages"]; exists {
		payload["messages"] = projectChatMessageItems(messages, nil)
	}
	if groups, exists := payload["conversationMessagesList"]; exists {
		payload["conversationMessagesList"] = projectChatConversationMessageGroups(groups)
	}

	switch result := payload["result"].(type) {
	case map[string]any:
		projectedResult := cloneStringAnyMap(result)
		if messages, exists := projectedResult["messages"]; exists {
			projectedResult["messages"] = projectChatMessageItems(messages, nil)
		}
		if groups, exists := projectedResult["conversationMessagesList"]; exists {
			projectedResult["conversationMessagesList"] = projectChatConversationMessageGroups(groups)
		}
		payload["result"] = projectedResult
	case []any, []map[string]any:
		payload["result"] = projectChatMessageItems(result, nil)
	}
	return payload
}

func projectChatConversationMessageGroups(value any) any {
	groups, ok := chatMessageMapItems(value)
	if !ok {
		return value
	}
	projected := make([]any, 0, len(groups))
	for _, group := range groups {
		projectedGroup := cloneStringAnyMap(group)
		context := map[string]any{}
		if conversationID, exists := group["openConversationId"]; exists {
			context["openConversationId"] = conversationID
		}
		if title, exists := group["title"]; exists {
			context["conversationTitle"] = title
		}
		if singleChat, exists := group["singleChat"]; exists {
			context["singleChat"] = singleChat
		}
		if messages, exists := group["messages"]; exists {
			projectedGroup["messages"] = projectChatMessageItems(messages, context)
		}
		projected = append(projected, projectedGroup)
	}
	return projected
}

func projectChatMessageItems(value any, context map[string]any) any {
	items, ok := chatMessageMapItems(value)
	if !ok {
		return value
	}
	projected := make([]any, 0, len(items))
	for _, item := range items {
		projected = append(projected, projectChatMessageItem(item, context))
	}
	return projected
}

func chatMessageMapItems(value any) ([]map[string]any, bool) {
	switch items := value.(type) {
	case []map[string]any:
		return items, true
	case []any:
		mapped := make([]map[string]any, 0, len(items))
		for _, item := range items {
			message, ok := item.(map[string]any)
			if !ok {
				return nil, false
			}
			mapped = append(mapped, message)
		}
		return mapped, true
	default:
		return nil, false
	}
}

func projectChatMessageItem(item map[string]any, context map[string]any) map[string]any {
	if !withinProjectionBudget(item) {
		// Not in dws: see budget.go.
		return boundedMessageItem(item, context)
	}
	projected := make(map[string]any, len(item)+len(context)+8)
	for key, value := range item {
		projected[key] = value
	}
	for key, value := range context {
		if _, exists := projected[key]; !exists {
			projected[key] = value
		}
	}
	for key, value := range chatmsg.ProjectMessageV1(projected, true) {
		if key == "messageId" || key == "text" {
			projected[key] = value
			continue
		}
		if _, exists := projected[key]; !exists {
			projected[key] = value
		}
	}
	if value, exists := item["openMessageId"]; exists {
		projected["openMessageId"] = value
	} else if value, exists := projected["messageId"]; exists {
		projected["openMessageId"] = value
	}
	if value, exists := item["content"]; exists {
		projected["content"] = value
	} else if value, exists := projected["text"]; exists {
		projected["content"] = value
	}
	return projected
}

func defaultChatMessageListTime() string {
	return time.Now().In(shanghaiLocation()).Format("2006-01-02 15:04:05")
}

// sanitizeTitleFromText derives a safe title from message text.
// When the user doesn't provide --title, the text content (which may contain
// URLs with percent-encoded characters like %3D, %26) is used as title.
// The title field has stricter validation on the server side (128 bytes max),
// so we strip or truncate content that is likely to be rejected.
func sanitizeTitleFromText(text string) (title string) {
	const maxTitleBytes = 100
	const maxTitleRunes = 30 // conservative: 30 CJK chars = 90 bytes, leaving room for "..."
	const fallbackTitle = "消息"

	if strings.TrimSpace(text) == "" {
		return fallbackTitle
	}

	// If text contains a URL, use only the portion before the URL as title.
	for _, prefix := range []string{"https://", "http://"} {
		if idx := strings.Index(text, prefix); idx > 0 {
			candidate := strings.TrimSpace(text[:idx])
			if candidate != "" {
				return truncateTitleToBytes(candidate, maxTitleBytes, maxTitleRunes)
			}
		}
	}

	// If the entire text is a URL, use a generic title.
	if strings.HasPrefix(text, "https://") || strings.HasPrefix(text, "http://") {
		return fallbackTitle
	}

	// Final fallback: if the result contains percent-encoded sequences
	// that the server may reject, use a generic title.
	if strings.Contains(text, "%") {
		return fallbackTitle
	}

	// No URL — truncate to safe length.
	return truncateTitleToBytes(text, maxTitleBytes, maxTitleRunes)
}

// truncateTitleToBytes truncates a title string ensuring it doesn't exceed
// maxBytes in UTF-8 encoding. It also limits by rune count for readability.
func truncateTitleToBytes(s string, maxBytes, maxRunes int) string {
	runes := []rune(s)
	if len(runes) > maxRunes {
		runes = runes[:maxRunes]
	}
	result := string(runes)
	// Ensure we don't exceed byte limit
	for len(result) > maxBytes-3 { // reserve 3 bytes for "..."
		runes = runes[:len(runes)-1]
		result = string(runes)
	}
	if len([]rune(s)) > len(runes) {
		return result + "..."
	}
	return result
}

// marshalJSONRaw serializes v to JSON without escaping <, >, &.
func marshalJSONRaw(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	// Encode appends a trailing newline; trim it.
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// normalizeAtPlaceholders 统一文本中针对 ids 的 @ 占位符格式，消化 send 与 send-by-bot 之间的差异。
// wrapAngle=true：用户身份发消息（send），裸 @id 自动包成 <@id>；已有 <@id> 保持不变。
// wrapAngle=false：机器人发消息（send-by-bot），<@id> 自动剥离为 @id。
// 仅替换 ids 中实际声明的标识，避免误伤 markdown 中其他 <...> 内容。
func normalizeAtPlaceholders(text string, ids []string, wrapAngle bool) string {
	const sentinelPrefix = "\x00DWS_AT_WRAPPED_"
	const sentinelSuffix = "\x00"
	for _, raw := range ids {
		id := strings.TrimSpace(raw)
		if id == "" {
			continue
		}
		wrapped := "<@" + id + ">"
		bare := "@" + id
		if wrapAngle {
			sentinel := sentinelPrefix + id + sentinelSuffix
			text = strings.ReplaceAll(text, wrapped, sentinel)
			text = strings.ReplaceAll(text, bare, wrapped)
			text = strings.ReplaceAll(text, sentinel, wrapped)
		} else {
			text = strings.ReplaceAll(text, wrapped, bare)
		}
	}
	return text
}

// NormalizeMessageMentions applies the placeholder convention required by the
// selected sender identity and ensures a declared @all is present in the body.
// Current-user messages use <@id>/<@all>; bot and webhook messages use
// @id/@mobile/@all.
func NormalizeMessageMentions(text string, ids []string, atAll, wrapAngle bool) string {
	text = normalizeAtPlaceholders(text, ids, wrapAngle)
	allPlaceholder := "@all"
	if wrapAngle {
		text = normalizeAtPlaceholders(text, []string{"all"}, true)
		allPlaceholder = "<@all>"
	} else {
		text = strings.ReplaceAll(text, "<@all>", "@all")
	}
	if atAll && !containsMessageMention(text, allPlaceholder) {
		text = allPlaceholder + " " + text
	}
	return text
}

// applyCurrentUserGroupMentions keeps the body placeholders and
// send_personal_message mention arguments aligned for send and reply.
func applyCurrentUserGroupMentions(params map[string]any, text, rawOpenIDs string, atAll bool) string {
	var atOpenIDs []string
	if rawOpenIDs != "" {
		atOpenIDs = strings.Split(rawOpenIDs, ",")
	}
	if atAll && !strings.Contains(text, "<@all>") {
		text = "<@all> " + text
	}
	text = normalizeAtPlaceholders(text, atOpenIDs, true)
	if atAll {
		params["atAll"] = true
	}
	if len(atOpenIDs) > 0 {
		params["atOpenDingTalkIds"] = atOpenIDs
	}
	return text
}

func addMissingCurrentUserMentionPlaceholders(text, rawOpenIDs string) string {
	if rawOpenIDs == "" {
		return text
	}
	missing := make([]string, 0)
	probeText := text
	for _, id := range parseCSVValues(rawOpenIDs) {
		placeholder := "<@" + id + ">"
		if strings.Contains(probeText, placeholder) {
			continue
		}
		missing = append(missing, placeholder)
		probeText += placeholder
	}
	if len(missing) == 0 {
		return text
	}
	prefix := strings.Join(missing, " ")
	if strings.HasPrefix(text, "<@all> ") {
		return "<@all> " + prefix + " " + strings.TrimPrefix(text, "<@all> ")
	}
	return prefix + " " + text
}

func containsMessageMention(text, placeholder string) bool {
	if strings.HasPrefix(placeholder, "<") {
		return strings.Contains(text, placeholder)
	}
	for searchFrom := 0; ; {
		offset := strings.Index(text[searchFrom:], placeholder)
		if offset < 0 {
			return false
		}
		end := searchFrom + offset + len(placeholder)
		if end == len(text) {
			return true
		}
		next, _ := utf8.DecodeRuneInString(text[end:])
		if !unicode.IsLetter(next) && !unicode.IsDigit(next) &&
			next != '_' && next != '-' {
			return true
		}
		searchFrom = end
	}
}

func cloneStringAnyMap(src map[string]any) map[string]any {
	dst := make(map[string]any, len(src))
	for key, value := range src {
		dst[key] = value
	}
	return dst
}

func unmarshalJSONUseNumber(text string, v any) error {
	dec := json.NewDecoder(strings.NewReader(text))
	dec.UseNumber()
	return dec.Decode(v)
}

// ParseChatA2UIMessages uses the same payload parser as the native card leaf.
func ParseChatA2UIMessages(raw string) ([]string, error) { return parseA2UIMessages(raw) }

// PrepareChatReplyMentions reuses the native reply's normalization and missing
// placeholder insertion before adapting the resulting body to the sender.
func PrepareChatReplyMentions(text string, ids []string, atAll, user bool) string {
	text = NormalizeMessageMentions(text, ids, atAll, true)
	text = addMissingCurrentUserMentionPlaceholders(text, strings.Join(ids, ","))
	if !user {
		text = NormalizeMessageMentions(text, ids, atAll, false)
	}
	return text
}

func parseCSVValues(raw string) []string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil
	}
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		var values []string
		if err := json.Unmarshal([]byte(raw), &values); err == nil {
			return cleanStringValues(values)
		}
		raw = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(raw, "["), "]"))
	}
	parts := strings.Split(raw, ",")
	return cleanStringValues(parts)
}

func cleanStringValues(parts []string) []string {
	values := make([]string, 0, len(parts))
	for _, p := range parts {
		v := strings.Trim(strings.TrimSpace(p), `"'`)
		if v != "" {
			values = append(values, v)
		}
	}
	return values
}

var agoalLoadLocation = time.LoadLocation

func shanghaiLocation() *time.Location {
	loc, err := agoalLoadLocation("Asia/Shanghai")
	if err != nil {
		return time.FixedZone("CST", 8*3600)
	}
	return loc
}
