// Verbatim declarations copied from github.com/DingTalk-Real-AI/dingtalk-workspace-cli
// tag v1.0.62-beta.8 (Apache-2.0; see clicompat/NOTICE). Generated by
// clicompat_excerpts.py: each declaration, doc comment included, is byte for
// byte the dws source at the file and line listed; nothing else is in this
// file except the package clause and imports.
//
//	func replyResponseValue                      internal/shortcut/chat/lark_alignment.go:333
//	func findOpenDingTalkID                      internal/shortcut/chat/lark_alignment.go:386
//	func findMessageSenderOpenDingTalkID         internal/shortcut/chat/lark_alignment.go:419
//	func shortcutMessageMaps                     internal/shortcut/chat/lark_alignment.go:437
//	func shortcutString                          internal/shortcut/chat/chat_group.go:1701
//	func appendUniqueShortcutString              internal/shortcut/chat/chat_group.go:1719
//	func uniqueShortcutStrings                   internal/shortcut/chat/chat_message.go:1525
//	func containsCurrentUserMentionToken         internal/shortcut/chat/unified_send.go:293
//	func currentUserMentionBodyIDs               internal/shortcut/chat/unified_send.go:312
//	func addMessagesSendUserTarget               internal/shortcut/chat/unified_send.go:799
//
// internal/shortcut/chat is not vendored (its files import cobra and most of dws).

package clicompat

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/shortcut/targetresolver"
)

func replyResponseValue(data map[string]any, keys ...string) any {
	scopes := []map[string]any{data}
	for _, wrapper := range []string{"result", "data"} {
		if nested, ok := data[wrapper].(map[string]any); ok {
			scopes = append(scopes, nested)
		}
	}
	for _, scope := range scopes {
		for _, key := range keys {
			if value, ok := scope[key]; ok && value != nil {
				if text, isString := value.(string); !isString || strings.TrimSpace(text) != "" {
					return value
				}
			}
		}
	}
	return nil
}

func findOpenDingTalkID(value any) string {
	switch typed := value.(type) {
	case map[string]any:
		for _, key := range []string{"senderOpenDingTalkId", "senderOpenDingtalkId", "openDingTalkId", "openDingtalkId"} {
			if candidate := strings.TrimSpace(fmt.Sprint(typed[key])); candidate != "" && candidate != "<nil>" {
				return candidate
			}
		}
		for _, child := range typed {
			if candidate := findOpenDingTalkID(child); candidate != "" {
				return candidate
			}
		}
	case []any:
		for _, child := range typed {
			if candidate := findOpenDingTalkID(child); candidate != "" {
				return candidate
			}
		}
	case []map[string]any:
		for _, child := range typed {
			if candidate := findOpenDingTalkID(child); candidate != "" {
				return candidate
			}
		}
	}
	return ""
}

// findMessageSenderOpenDingTalkID intentionally inspects only sender identity
// fields. A message may contain unrelated openDingTalkId values in mentions,
// quoted content, cards, or attachments; recursively taking the first identity
// from the whole payload could reply with the wrong source sender.
func findMessageSenderOpenDingTalkID(message map[string]any) string {
	for _, key := range []string{
		"senderOpenDingTalkId",
		"senderOpenDingtalkId",
		"senderOpenId",
	} {
		if candidate := strings.TrimSpace(fmt.Sprint(message[key])); candidate != "" && candidate != "<nil>" {
			return candidate
		}
	}
	for _, key := range []string{"sender", "senderInfo", "senderUser"} {
		if candidate := findOpenDingTalkID(message[key]); candidate != "" {
			return candidate
		}
	}
	return ""
}

func shortcutMessageMaps(data map[string]any) []map[string]any {
	if data == nil {
		return nil
	}
	scopes := []map[string]any{data}
	for _, key := range []string{"result", "data"} {
		if inner, ok := data[key].(map[string]any); ok {
			scopes = append(scopes, inner)
		}
	}
	for _, scope := range scopes {
		for _, key := range []string{"result", "data", "messages", "list", "items", "records"} {
			switch values := scope[key].(type) {
			case []any:
				out := make([]map[string]any, 0, len(values))
				for _, value := range values {
					if mapped, ok := value.(map[string]any); ok {
						out = append(out, mapped)
					}
				}
				return out
			case []map[string]any:
				return values
			}
		}
	}
	return nil
}

func shortcutString(value map[string]any, keys ...string) string {
	for _, key := range keys {
		switch typed := value[key].(type) {
		case string:
			if text := strings.TrimSpace(typed); text != "" {
				return text
			}
		case float64:
			return strconv.FormatFloat(typed, 'f', -1, 64)
		case int:
			return strconv.Itoa(typed)
		case int64:
			return strconv.FormatInt(typed, 10)
		}
	}
	return ""
}

func appendUniqueShortcutString(values []string, candidate string) []string {
	for _, value := range values {
		if value == candidate {
			return values
		}
	}
	return append(values, candidate)
}

func uniqueShortcutStrings(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			out = appendUniqueShortcutString(out, value)
		}
	}
	return out
}

func containsCurrentUserMentionToken(body, id string) bool {
	placeholder := "@" + id
	for searchFrom := 0; ; {
		offset := strings.Index(body[searchFrom:], placeholder)
		if offset < 0 {
			return false
		}
		end := searchFrom + offset + len(placeholder)
		if end == len(body) {
			return true
		}
		next, _ := utf8.DecodeRuneInString(body[end:])
		if !unicode.IsLetter(next) && !unicode.IsDigit(next) && next != '_' && next != '-' {
			return true
		}
		searchFrom = end
	}
}

func currentUserMentionBodyIDs(body string) []string {
	ids := make([]string, 0)
	for searchFrom := 0; ; {
		offset := strings.IndexByte(body[searchFrom:], '@')
		if offset < 0 {
			break
		}
		start := searchFrom + offset + 1
		end := start
		for end < len(body) {
			current := body[end]
			if (current < 'a' || current > 'z') &&
				(current < 'A' || current > 'Z') &&
				(current < '0' || current > '9') {
				break
			}
			end++
		}
		id := body[start:end]
		if targetresolver.LooksLikeCurrentDOpenDingTalkID(id) {
			ids = appendUniqueShortcutString(ids, id)
		}
		searchFrom = end
	}
	return ids
}

func addMessagesSendUserTarget(params map[string]any, group, openID string) {
	if group != "" {
		params["openConversationId"] = group
		return
	}
	params["receiverOpenDingTalkId"] = openID
}
