// Verbatim declarations copied from github.com/DingTalk-Real-AI/dingtalk-workspace-cli
// tag v1.0.62-beta.8 (Apache-2.0; see clicompat/NOTICE). Generated by
// clicompat_excerpts.py: each declaration, doc comment included, is byte for
// byte the dws source at the file and line listed; nothing else is in this
// file except the package clause and imports.
//
//	func detectBusinessError                     internal/app/runner.go:1209
//	func detectBusinessErrorAtDepth              internal/app/runner.go:1213
//	func detectNestedBusinessError               internal/app/runner.go:1237
//	func extractMCPErrorMessage                  internal/app/runner.go:1261
//	var dingRobotRejectionPattern                internal/app/server_failure_classifier.go:25
//	type serverFailureClass                      internal/app/server_failure_classifier.go:27
//	func classifyServerFailure                   internal/app/server_failure_classifier.go:39
//	func newServerFailureAPIError                internal/app/server_failure_classifier.go:131
//	func errorInfoFromExecutionError             internal/app/root.go:408 (modified, see below)
//	func errorTypeForExitCode                    internal/app/root.go:497
//	func interruptionExitCode                    internal/app/signal.go:39
//	type processInterruption                     internal/app/signal.go:46
//	method processInterruption.Error             internal/app/signal.go:51
//	method processInterruption.Unwrap            internal/app/signal.go:59
//	method processInterruption.ExitCode          internal/app/signal.go:78
//	method processInterruption.Subtype           internal/app/signal.go:82
//	type authRefreshFailureError                 internal/app/auth_refresh_retry.go:35
//	method authRefreshFailureError.Error         internal/app/auth_refresh_retry.go:40
//	method authRefreshFailureError.Unwrap        internal/app/auth_refresh_retry.go:44
//
// internal/app is not vendored (its files import cobra and most of dws).
//
// Modification: errorInfoFromExecutionError names helpers.CLIError as
// CLIError, because the helpers declarations are copied into this package
// (dws_helpers.go) rather than vendored as package helpers.

package clicompat

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"os"
	"regexp"
	"strings"
	"syscall"
	"time"

	apperrors "github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/errors"
	"github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/output"
	"github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/transport"
)

// detectBusinessError checks the MCP response content for DingTalk business
// errors (success=false + errorCode/errorMsg) that are not flagged at the MCP
// protocol level. Returns the error message, or "" if the response is OK.
func detectBusinessError(content map[string]any) string {
	return detectBusinessErrorAtDepth(content, 0)
}

func detectBusinessErrorAtDepth(content map[string]any, depth int) string {
	if content == nil || depth > 8 {
		return ""
	}
	success, ok := content["success"]
	if !ok {
		return detectNestedBusinessError(content, depth)
	}
	b, ok := success.(bool)
	if !ok || b {
		return detectNestedBusinessError(content, depth)
	}
	if nested := detectNestedBusinessError(content, depth); nested != "" {
		return nested
	}
	if msg, ok := content["errorMsg"].(string); ok && strings.TrimSpace(msg) != "" {
		return strings.TrimSpace(msg)
	}
	if code, ok := content["errorCode"].(string); ok && strings.TrimSpace(code) != "" {
		return "business error: code " + strings.TrimSpace(code)
	}
	return "business error: success=false"
}

func detectNestedBusinessError(content map[string]any, depth int) string {
	for _, key := range []string{"content", "result", "data"} {
		switch child := content[key].(type) {
		case map[string]any:
			if msg := detectBusinessErrorAtDepth(child, depth+1); msg != "" {
				return msg
			}
		case []any:
			for _, item := range child {
				childMap, ok := item.(map[string]any)
				if !ok {
					continue
				}
				if msg := detectBusinessErrorAtDepth(childMap, depth+1); msg != "" {
					return msg
				}
			}
		}
	}
	return ""
}

// extractMCPErrorMessage builds an error message from a ToolCallResult with
// isError=true. It extracts text from content blocks when available.
func extractMCPErrorMessage(result transport.ToolCallResult) string {
	// Try text from content blocks first.
	for _, block := range result.Blocks {
		text := strings.TrimSpace(block.Text)
		if text != "" {
			return text
		}
	}
	// Try stringified content map.
	if msg, ok := result.Content["message"].(string); ok && strings.TrimSpace(msg) != "" {
		return strings.TrimSpace(msg)
	}
	if msg, ok := result.Content["error"].(string); ok && strings.TrimSpace(msg) != "" {
		return strings.TrimSpace(msg)
	}
	return "MCP tool returned an error response"
}

// Match an explicit rejection of robotCode itself, not an unrelated invalid
// parameter elsewhere in the error or a phrase stitched across diagnostics.
var dingRobotRejectionPattern = regexp.MustCompile(`(?i)\b(?:robotcode(?:\s*:\s*|\s+(?:is\s+(?:in\s+)?)?)(?:invalid|not\s+valid|not\s+in\s+(?:the\s+)?org(?:anization)?)|invalid\s+robotcode)\b`)

type serverFailureClass struct {
	message          string
	reason           string
	origin           string
	stage            string
	hint             string
	actions          []string
	operation        string
	retryable        *bool
	executionStarted *bool
}

func classifyServerFailure(message, serverKey, tool string, diag apperrors.ServerDiagnostics) (serverFailureClass, bool) {
	code := strings.ToUpper(strings.TrimSpace(diag.ServerErrorCode))
	detail := strings.ToLower(strings.TrimSpace(diag.TechnicalDetail))
	text := strings.ToLower(strings.TrimSpace(message))
	combined := text + " " + detail

	if strings.EqualFold(strings.TrimSpace(serverKey), "ding") &&
		(strings.EqualFold(strings.TrimSpace(tool), "send_ding_message") ||
			strings.EqualFold(strings.TrimSpace(tool), "recall_ding_message")) &&
		(dingRobotRejectionPattern.MatchString(text) || dingRobotRejectionPattern.MatchString(detail)) {
		retryable := false
		executionStarted := false
		return serverFailureClass{
			message:          "企业机器人不在当前组织或未处于可用状态",
			reason:           "robot_not_in_org",
			origin:           "dingtalk_api",
			stage:            "precondition_rejected",
			operation:        "ding/" + strings.TrimSpace(tool),
			retryable:        &retryable,
			executionStarted: &executionStarted,
			hint:             "请提供当前组织内有效且已发布的 robot-code 后重新发起请求。",
			actions: []string{
				"停止本次机器人 DING；禁止尝试或替换为其他机器人（包括其他 robot-code）；不要搜索 dev/devapp、配置、其他 profile 或替换发送通道",
			},
		}, true
	}

	if code == "999" &&
		(strings.Contains(combined, "nullpointerexception") || strings.Contains(combined, "system error")) {
		classified := serverFailureClass{
			message: message,
			reason:  "upstream_internal_error",
			origin:  "dingtalk_api",
			stage:   "upstream_execution",
			hint:    "上游服务发生内部异常；请保留 Trace ID 和 Server Code，确认操作结果后再决定是否重试。",
			actions: []string{
				"检查目标资源的当前状态，确认本次操作是否已经生效",
				"状态未确认前不要直接重试写操作",
				"持续失败时携带 Trace ID 和 Server Code 联系服务端排查",
			},
		}
		if strings.EqualFold(strings.TrimSpace(serverKey), "todo") &&
			strings.EqualFold(strings.TrimSpace(tool), "create_personal_todo") {
			retryable := false
			classified.operation = "todo/create_personal_todo"
			classified.retryable = &retryable
			classified.hint = "待办服务发生内部异常，创建结果未知；请先查询是否已创建相同待办，再决定是否重试。"
			classified.actions = []string{
				"查询近期由自己创建的待办，核对标题、执行人和截止时间",
				"确认没有创建成功后再重新提交",
				"持续失败时携带 Trace ID 和 Server Code 联系服务端排查",
			}
		}
		return classified, true
	}

	if code == "NETWORK_ERROR" ||
		strings.Contains(detail, "statuscode.unavailable") ||
		strings.Contains(detail, "connection refused") {
		classified := serverFailureClass{
			message: "MCP 后端依赖暂时不可用",
			reason:  "backend_dependency_unavailable",
			origin:  "mcp_gateway",
			stage:   "backend_dependency",
			hint:    "请求参数无需修改；请使用相同参数稍后重试。持续失败时请提供 Trace ID 排查 MCP 服务。",
			actions: []string{
				"使用相同参数重试一次",
				"持续失败时保留 Trace ID 并排查 MCP 后端依赖",
			},
		}
		if strings.Contains(detail, "querytoolmeta") {
			classified.message = "MCP 后端元数据服务暂时不可用"
			classified.stage = "tool_metadata_lookup"
		}
		return classified, true
	}

	if code == "PARAM_ERROR" ||
		strings.Contains(text, "opencid or cid is required") ||
		strings.Contains(text, "openconversationid") && strings.Contains(text, "required") {
		return serverFailureClass{
			message: message,
			reason:  "invalid_request",
			origin:  "dingtalk_api",
			stage:   "tool_validation",
			hint:    "请求未通过后端参数校验；请核对当前 leaf Help/Schema 和稳定 ID 类型后重试。",
		}, true
	}

	return serverFailureClass{}, false
}

func newServerFailureAPIError(
	message string,
	fallbackReason string,
	fallbackHint string,
	serverKey string,
	tool string,
	diag apperrors.ServerDiagnostics,
) error {
	opts := []apperrors.Option{
		apperrors.WithOperation("tools/call"),
		apperrors.WithReason(fallbackReason),
		apperrors.WithServerKey(serverKey),
		apperrors.WithHint(fallbackHint),
		apperrors.WithActions("持续失败时保留 Trace ID 和 Server Code 联系服务端排查"),
		apperrors.WithServerDiag(diag),
	}
	if classified, ok := classifyServerFailure(message, serverKey, tool, diag); ok {
		message = classified.message
		opts = append(opts,
			apperrors.WithReason(classified.reason),
			apperrors.WithOrigin(classified.origin),
			apperrors.WithFailureStage(classified.stage),
			apperrors.WithHint(classified.hint),
			apperrors.WithActions(classified.actions...),
		)
		if classified.operation != "" {
			opts = append(opts, apperrors.WithOperation(classified.operation))
		}
		if classified.retryable != nil {
			opts = append(opts, apperrors.WithRetryable(*classified.retryable))
		}
		if classified.executionStarted != nil {
			opts = append(opts, apperrors.WithExecutionStarted(*classified.executionStarted))
		}
	}
	return apperrors.NewAPI(message, opts...)
}

// errorInfoFromExecutionError projects the repository error model into the unified
// failure body. Exit code and category are derived from the same error value,
// preventing the wire and process status from drifting apart.
func errorInfoFromExecutionError(err error) *output.ErrorInfo {
	exitCode := apperrors.ExitCode(err)
	info := &output.ErrorInfo{
		Type:     errorTypeForExitCode(exitCode),
		ExitCode: exitCode,
		Message:  err.Error(),
	}
	var interrupted *processInterruption
	if stderrors.As(err, &interrupted) && interrupted != nil {
		info.Type = "internal"
		info.Subtype = interrupted.Subtype()
		return info
	}
	if stderrors.Is(err, context.DeadlineExceeded) {
		info.Subtype = "deadline_exceeded"
	}
	var cliErr *CLIError
	if stderrors.As(err, &cliErr) && cliErr != nil {
		info.UpstreamCode = cliErr.Code
		info.Hint = cliErr.Suggestion
		info.Operation = cliErr.Operation
	}
	var callErr *transport.CallError
	if stderrors.As(err, &callErr) && callErr != nil {
		info.HTTPStatus = callErr.HTTPStatus
		info.RPCCode = callErr.RPCCode
		info.Stage = string(callErr.Stage)
		if callErr.RequestID != "" {
			info.RequestID = callErr.RequestID
		} else if callErr.TraceID != "" {
			info.RequestID = callErr.TraceID
		}
	}
	var typed *apperrors.Error
	if !stderrors.As(err, &typed) || typed == nil {
		return info
	}
	if typed.Category == apperrors.CategoryPartial {
		// An error lacks the item-level data required by partial_failure.
		// Callers must use output.Partial; fail closed consistently otherwise.
		info.Type = string(apperrors.CategoryInternal)
	} else {
		info.Type = string(typed.Category)
	}
	info.Subtype = typed.Reason
	if typed.Hint != "" {
		info.Hint = typed.Hint
	}
	info.Actions = apperrors.RecoveryActions(err)
	info.Retryable = typed.RetryableSet && typed.Retryable
	info.RetryAfterSeconds = typed.RetryAfterSeconds
	if typed.RPCCode != 0 {
		info.RPCCode = typed.RPCCode
	}
	if typed.ServerDiag.TraceID != "" {
		info.TraceID = typed.ServerDiag.TraceID
	}
	if typed.Operation != "" {
		info.Operation = typed.Operation
	}
	info.ServerKey = typed.ServerKey
	info.Origin = typed.Origin
	if typed.FailureStage != "" {
		info.Stage = typed.FailureStage
	}
	info.ExecutionStarted = typed.ExecutionStarted
	if typed.NextRetryAt != nil {
		info.NextRetryAt = typed.NextRetryAt.UTC().Format(time.RFC3339)
	}
	info.AvailableFlags = append([]string(nil), typed.AvailableFlags...)
	info.SnapshotPath = typed.Snapshot
	info.Details = typed.Details
	if len(typed.RPCData) > 0 {
		var rpcData any
		if json.Unmarshal(typed.RPCData, &rpcData) == nil {
			info.RPCData = rpcData
		}
	}
	info.TechnicalDetail = typed.ServerDiag.TechnicalDetail
	info.FriendlyHint, info.ActionURL = apperrors.ServerGuidance(typed.ServerDiag)
	if typed.Cause != nil {
		info.Cause = typed.Cause.Error()
	}
	if typed.ServerDiag.ServerErrorCode != "" {
		info.UpstreamCode = typed.ServerDiag.ServerErrorCode
	}
	return info
}

func errorTypeForExitCode(code int) string {
	switch code {
	case 1:
		return "api"
	case 2:
		return "auth"
	case 3:
		return "validation"
	case 4:
		return "permission"
	case 6:
		return "discovery"
	default:
		return "internal"
	}
}

func interruptionExitCode(sig os.Signal) int {
	if sig == syscall.SIGTERM {
		return 143
	}
	return 130
}

type processInterruption struct {
	signal os.Signal
	detail error
}

func (e *processInterruption) Error() string {
	message := fmt.Sprintf("process interrupted by %s", e.signal)
	if e.detail != nil {
		return fmt.Sprintf("%s: %v", message, e.detail)
	}
	return message
}

func (e *processInterruption) Unwrap() error { return context.Canceled }

func (e *processInterruption) ExitCode() int {
	return interruptionExitCode(e.signal)
}

func (e *processInterruption) Subtype() string {
	if e.signal == syscall.SIGTERM {
		return "terminated"
	}
	return "cancelled_by_user"
}

type authRefreshFailureError struct {
	rejection error
	refresh   error
}

func (e *authRefreshFailureError) Error() string {
	return "automatic access token refresh failed"
}

func (e *authRefreshFailureError) Unwrap() []error {
	if e == nil {
		return nil
	}
	return []error{e.rejection, e.refresh}
}
