// Code generated by tools/eventcatalog from dingtalk-workspace-cli @ 7de51a87a13f internal/event/personal/registry.go. DO NOT EDIT.

package dws

var eventCatalog = []EventDefinition{
	{Key: "user_im_message_receive_at", DisplayName: "@我的消息", Description: "当前用户被 @ 的消息", Category: "im", RuleType: "at", Status: "enabled", Public: true},
	{Key: "user_im_message_receive_o2o", DisplayName: "指定单聊消息", Description: "当前用户与指定用户的单聊消息", Category: "im", RuleType: "singleChat", Status: "enabled", Public: true},
	{Key: "user_im_message_receive_group", DisplayName: "指定群消息", Description: "当前用户所在指定会话的消息", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_message_receive_user", DisplayName: "指定发送人消息", Description: "当前用户收到的指定用户发送的消息", Category: "im", RuleType: "sender", Status: "enabled", Public: true},
	{Key: "user_im_message_receive_o2o_all", DisplayName: "全部单聊消息", Description: "当前用户收到的所有单聊消息", Category: "im", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_im_message_receive_group_all", DisplayName: "全部群消息", Description: "当前用户收到的所有群聊消息", Category: "im", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_im_message_read_o2o", DisplayName: "指定单聊消息已读", Description: "当前用户在指定单聊中发送的消息被对方已读", Category: "im", RuleType: "singleChat", Status: "enabled", Public: true},
	{Key: "user_im_message_read_group", DisplayName: "指定群消息已读", Description: "当前用户在指定群聊中发送的消息被已读", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_message_recall_o2o", DisplayName: "指定单聊消息撤回", Description: "指定单聊中的消息被撤回", Category: "im", RuleType: "singleChat", Status: "enabled", Public: true},
	{Key: "user_im_message_recall_group", DisplayName: "指定群消息撤回", Description: "指定群聊中的消息被撤回", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_message_reaction_o2o", DisplayName: "指定单聊消息表情回应", Description: "指定单聊中的消息收到表情回应（贴表情）", Category: "im", RuleType: "singleChat", Status: "enabled", Public: true},
	{Key: "user_im_message_reaction_group", DisplayName: "指定群消息表情回应", Description: "指定群聊中的消息收到表情回应（贴表情）", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_group_updated", DisplayName: "群标题变更", Description: "指定群聊的标题发生变更", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_group_member_added", DisplayName: "群成员加入", Description: "指定群聊有成员加入", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_group_member_exited", DisplayName: "群成员退出", Description: "指定群聊有成员退出", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_im_group_disbanded", DisplayName: "群解散", Description: "指定群聊被解散", Category: "im", RuleType: "group", Status: "enabled", Public: true},
	{Key: "user_oa_approval_task_created", DisplayName: "审批任务创建", Description: "审批任务创建，发送给审批人", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_task_finished", DisplayName: "审批任务完成", Description: "审批任务已完成", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_task_redirected", DisplayName: "审批人任务转交", Description: "审批任务已转交", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_instance_started", DisplayName: "发起审批单", Description: "审批实例已发起", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_instance_cc", DisplayName: "审批单抄送", Description: "审批实例到达抄送节点，发送给被抄送人", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_instance_terminated", DisplayName: "审批单终止", Description: "审批实例已终止", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_oa_approval_instance_finished", DisplayName: "审批单完成", Description: "审批实例完成，发送给审批单发起人", Category: "oa", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_voip_call_receive_invite", DisplayName: "语音通话接收邀请", Description: "被叫用户收到语音通话邀请，通话已切换为会议模式", Category: "voip", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_todo_task_create", DisplayName: "待办创建", Description: "当前用户作为创建者、执行者或参与者的待办被创建", Category: "todo", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_todo_task_update", DisplayName: "待办更新", Description: "当前用户作为创建者、执行者或参与者的待办被更新", Category: "todo", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_todo_task_delete", DisplayName: "待办删除", Description: "当前用户作为创建者、执行者或参与者的待办被删除", Category: "todo", RuleType: "all", Status: "enabled", Public: true},
	{Key: "user_card_action_triggered", DisplayName: "互动卡片回调", Description: "当前用户提交或操作互动卡片后收到的回调；结构化上下文位于 payload.body.actionData.context", Category: "card", RuleType: "all", Status: "enabled", Public: true},
}
