CREATE TABLE IF NOT EXISTS sandbox_send_receipt (
    id TEXT NOT NULL,
    workspace_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    task_id UUID NOT NULL,
    issue_id UUID,
    client_action_id TEXT NOT NULL,
    input JSONB NOT NULL,
    payload_hash TEXT NOT NULL,
    idempotency_key TEXT NOT NULL DEFAULT '',
    target_conversation_id TEXT NOT NULL DEFAULT '',
    recipient_open_dingtalk_id TEXT NOT NULL DEFAULT '',
    observed_state TEXT NOT NULL,
    observation_revision BIGINT NOT NULL DEFAULT 1,
    state TEXT NOT NULL CHECK (state IN ('pending', 'provider_accepted', 'delivered', 'failed', 'unknown')),
    provider_task_id TEXT NOT NULL DEFAULT '',
    provider_conversation_id TEXT NOT NULL DEFAULT '',
    provider_message_id TEXT NOT NULL DEFAULT '',
    delivery_hook_completed_at TIMESTAMPTZ,
    error_code TEXT NOT NULL DEFAULT '',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    lease_token UUID,
    lease_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
