-- Direct artifacts reuse attachment and Storage; this ledger owns immutable provenance and upload/cleanup state.
CREATE TABLE IF NOT EXISTS employee_task_artifact (
    attachment_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    tenant_org_id text NOT NULL CHECK (char_length(tenant_org_id) BETWEEN 1 AND 128),
    scene_id uuid NOT NULL,
    task_id uuid NOT NULL,
    run_id uuid NOT NULL,
    queue_task_id uuid NOT NULL,
    goal_revision bigint NOT NULL CHECK (goal_revision > 0),
    filename text NOT NULL CHECK (octet_length(filename) BETWEEN 1 AND 512),
    content_type text NOT NULL CHECK (octet_length(content_type) BETWEEN 1 AND 256),
    sha256 text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size_bytes bigint NOT NULL CHECK (size_bytes BETWEEN 0 AND 104857600),
    storage_key text NOT NULL,
    storage_url text NOT NULL,
    stored_size_bytes bigint NOT NULL DEFAULT 0 CHECK (stored_size_bytes >= 0),
    encryption_scheme text NOT NULL DEFAULT 'employee-artifact-secretbox-v1',
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','ready','deleting','tombstoned')),
    lease_token uuid,
    lease_expires_at timestamptz,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    attempt_count integer NOT NULL DEFAULT 0,
    tombstone_pass integer NOT NULL DEFAULT 0,
    last_error text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    ready_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);
