CREATE TABLE IF NOT EXISTS employee_human_question (
 id uuid PRIMARY KEY,
 workspace_id uuid NOT NULL,
 agent_id uuid NOT NULL,
 tenant_org_id text NOT NULL,
 scene_id uuid NOT NULL,
 principal_id uuid NOT NULL,
 source_job_id uuid NOT NULL,
 source_receipt_id uuid NOT NULL,
 source_ref text NOT NULL,
 requester_ref text NOT NULL,
 operator_open_id text NOT NULL,
 task_id uuid,
 run_id uuid,
 goal_revision bigint NOT NULL DEFAULT 0,
 version integer NOT NULL DEFAULT 1,
 summary text NOT NULL,
 choice jsonb NOT NULL,
 card_public_id text NOT NULL,
 action_id text NOT NULL DEFAULT '',
 state text NOT NULL DEFAULT 'open',
 response_id uuid,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT employee_human_question_version CHECK (version > 0),
 CONSTRAINT employee_human_question_state CHECK (state IN ('open','deferred','answered','superseded','cancelled')),
 CONSTRAINT employee_human_question_run CHECK ((task_id IS NULL AND run_id IS NULL AND goal_revision=0) OR (task_id IS NOT NULL AND run_id IS NOT NULL AND goal_revision>0))
);
CREATE TABLE IF NOT EXISTS employee_human_response (
 id uuid PRIMARY KEY,
 question_id uuid NOT NULL,
 event_id text NOT NULL,
 input_surface text NOT NULL,
 requester_ref text NOT NULL,
 body jsonb NOT NULL,
 receipt_id uuid,
 job_id uuid,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT employee_human_response_surface CHECK (input_surface IN ('a2ui_action','chat_text'))
);
