from common import *

RD = {"D总": "director"}
RZ = {"冬翔": "zhujue"}
RT = {"D总": "director", "冬翔": "zhujue"}
INTERNAL_RE = r"scene_routine|dispatch_task|continue_task|steer_task|stop_task|read_task|Autopilot|(?<![A-Za-z])(Direct|queue|Run)(?![A-Za-z])"

CATEGORY = {"code": "T", "name": "办事与持续推进", "file": "T.json",
            "focus": "问与办、派活与进度、运行中纠正与停止、续接与 builds_on、文件交付、停滞提示、例行任务、Webhook、跨场域收集、计划续行"}

CASES = [
case(
    id="T-01", title="报销汇总表：派活 → 过两分钟催进度 → 出结果 → 同一件事再按类别出一份 → 道谢（BASE-TASK 真人版）",
    focus=["F5", "F3"], maps=["BASE-TASK"], scene="dm", conv="dm_director", roles=RD,
    x_run_window={"from": "10:30", "to": "13:30", "why": "「我两点前要给王雪」"},
    steps=[
        say("start", "D总", "9月出差那几笔帮我弄个报销汇总表，按人汇总，最后给个总数，我下午要转给王雪。弄成 Excel 或 CSV 发我都行\n9/03 东翔 高铁 杭州东-上海虹桥 73\n9/03 东翔 打车 46\n9/04 东翔 住宿 全季 1晚 389\n9/05 东翔 高铁 上海虹桥-杭州东 73\n9/03 周明 打车 58\n9/04 周明 住宿 亚朵 1晚 412\n9/04 周明 餐补 35\n9/05 周明 打车 96\n9/10 林晓 机票改签费 128\n9/10 林晓 住宿 如家 1晚 389\n9/11 林晓 打车 64\n9/11 林晓 餐补 115",
            w_reply(120, 150), match_key="9月出差那几笔帮我弄个报销汇总表"),
        say("urge", "D总", "好了没？我两点前要给王雪", w_reply(120, 10)),
        obs("done1", r"1,?878", since="start", timeout=480),
        say("more", "D总", "再按类别出一份：交通、住宿、餐补各多少，跟刚才那张放一个文件里", w_reply(120, 8), match_key="再按类别出一份"),
        obs("done2", r"1,?190", since="more", timeout=480),
        say("thanks", "D总", "可以，谢了", w_sil(60)),
    ],
    criteria="分人 581/601/696、合计 1878；类别 交通538/住宿1190/餐补150；催进度不编百分比或 ETA；续接为同一 Task 新 Run；致谢零派发。",
    checks=[
        chk("start", replies=[1, 2]),
        chk("urge", replies=[1, 1], exc=[r"\d{1,3}\s*%", r"预计.{0,8}\d+\s*(分钟|秒)"]),
        chk(["start", "urge", "done1"], inc=["581", "601", "696"]),
        chk(["more", "done2"], inc=["538", "150"]),
        chk("thanks", replies=[0, 1], maxc=30),
        calls(3), noeff("urge"), noeff("thanks"), runs(2),
    ],
    semantic=["接单不冒称已开始或已完成，口吻像同事", "进度来自实时任务状态，不编百分比或 ETA", "改签费、打车归入交通，口径合理",
              "续接沿用同一 Task 新 Run", "致谢不展开、不派发"],
    harness=[], status="ready", reason="现有 harness 即可跑（start 的 settle=150 用来让「催进度」晚两分多钟发出）",
    doc=doc("D总单聊。月初报销季，D总把 12 笔差旅流水贴给员工，要一份能直接转给财务王雪的表；过两分钟催进度，拿到表后再要一个维度，最后道谢。",
            "D总；小Q；王雪（财务）、冬翔、周明、林晓（流水里的人名）。",
            "对应 BASE-TASK。数字固定：冬翔 581、周明 601、林晓 696，合计 1878；交通 538、住宿 1190、餐补 150。",
            "start 派后台、自然接单；urge 实时读状态如实说，不编百分比；结果分人小计与合计；more 同一 Task 新 Run；thanks 不回或一句。",
            "数字都对、进度诚实、续接同一 Task、致谢零派发，就通过。", "existing。",
            "大概率部分通过：Qwen-Real 上续接曾新建 Task（same_task_runs 风险）。",
            "催进度挪到接单后约两分钟（真人不会 10 秒就催）；流水里 D总那几笔换成同事周明，避免把 D总写进报销单。")),
case(
    id="T-02", title="问 vs 办：能当场答的直接答，短文案直接写，要动钉盘才派活",
    focus=["F5"], maps=["BASE-TASK(反例)"], scene="dm", conv="dm_zhujue", roles=RZ,
    steps=[
        say("ask", "冬翔", "上周项目组团建的几笔你帮我看下，人均超没超 300：\n场地 2400\n大巴 1100\n午餐 1860\n饮料零食 386\n一共 18 个人",
            w_reply(120, 10), match_key="上周项目组团建的几笔你帮我看下"),
        say("note", "冬翔", "超了啊…那帮我写两句超标说明，我贴报销单备注里，别太长", w_reply(120, 10), match_key="那帮我写两句超标说明"),
        say("work", "冬翔", "行。另外在钉盘「行政/团建报销」下面建个文档，把这几笔和人均记上，回头财务要查", w_reply(180, 15),
            match_key="下面建个文档，把这几笔和人均记上"),
        obs("workdone", r"文档|钉盘|权限|没能|失败|没有建", since="work", timeout=480),
        say("thanks", "冬翔", "好嘞", w_sil(45), match_key="好嘞"),
    ],
    criteria="问题当场答（人均约 319，超标），短文案直接写，建文档才派后台并如实汇报结果，就通过。",
    checks=[
        chk("ask", replies=[1, 1], inc=["319"]), noeff("ask"),
        chk("note", replies=[1, 1], maxc=200), noeff("note"),
        chk(["work", "workdone"], replies=[1, 3], exc=[r"没有(这个|相关)?工具|找管理员|联系管理员"]),
        chk("thanks", replies=[0, 1], maxc=20), noeff("thanks"), calls(3),
    ],
    pending_checks=[{"evidence": "effect_for_step", "step": "work", "tools": ["dispatch_task"], "why": "正向断言第 3 步确实派了任务"}],
    semantic=["第一问直接给结论和依据，没派活也没说「我去查」", "超标说明两三句、能直接粘贴", "建文档派了后台，接单自然", "结果如实：成功给位置，失败说原因"],
    harness=[], ops=["routine_pause"], status="ready", reason="现有 harness 即可跑",
    doc=doc("东翔单聊。东翔把团建费用贴过来问人均超没超，接着要两句超标说明，再让员工在钉盘建文档。",
            "冬翔/东翔（项目负责人，组织了组内团建）；小Q。", "对照 GawkBot Rule Zero：问题当场答，只有动外部系统才开事项。合计 5746、18 人，人均约 319。",
            "ask 当场答超了、人均约 319；note 直接写两三句；work 派后台，接单一句，结果如实；thanks 不回或一句。",
            "前两问零派发、第三问派发且如实，就通过。", "existing。", "预计通过。", "真人常把「问一下」和「顺手办一下」混着说；与 T-01 构成相邻反例。")),
case(
    id="T-03", title="群里排值班，运行中补一句「周明那几天出差别排他」（BASE-STEER 真人版）",
    focus=["F5", "F1"], maps=["BASE-STEER"], scene="group", conv="group_t", roles=RT,
    steps=[
        say("ask", "冬翔", "帮我排下 10 月 19 号到 30 号华信现场支持的值班：我、林晓、周明、小周四个人轮，工作日每天一个人，周末不排。排好直接发群里，按日期一行一行列",
            w_reply(120, 8), at=["employee"], match_key="帮我排下 10 月 19 号到 30 号华信现场支持的值班"),
        say("fix", "冬翔", "哦对了 周明 20 号到 24 号在北京出差，那几天别排他", w_reply(120, 8), at=["employee"], match_key="周明 20 号到 24 号在北京出差"),
        obs("done", r"^(?=(?:[^\n]*\n){6})(?=[\s\S]*林晓)(?=[\s\S]*周明)", since="ask", timeout=480),
        say("thanks", "冬翔", "行 就按这个来", w_sil(60), at=["employee"]),
    ],
    criteria="群里只有一份值班表、10/20–10/23 没有周明；纠正走同一 Task，旧表不补发，就通过。",
    checks=[
        chk(["ask", "fix"], replies=[3, 3], exc=[r"(?<!\d)(10[/.-]|10月)?2[0-3](?!\d)\s*[日号]?[^\n]{0,15}周明"],
            note="接单 + 纠正确认 + 唯一一份结果，合并计数避免归属错位"),
        chk("thanks", replies=[0, 1], maxc=30), noeff("thanks"), runs(2), calls(3),
    ],
    pending_checks=[{"check": "send_within_s", "step": "fix", "max_s": 30, "why": "纠正必须在旧 Run 结束前送到，否则判 invalid_timing 重跑"}],
    semantic=["补充条件被当成对同一件事的纠正", "纠正确认是一句人话", "20–23 号没有周明，周末不排，四人大致均衡", "群里只有一份表（或明确的更正版）"],
    harness=[], status="ready", reason="现有 harness 即可跑；时序门槛待补（P1）",
    doc=doc("交付二组·项目推进群。东翔 @小Q 排华信现场支持值班；接单后十几秒想起漏了条件，补一句。",
            "冬翔/东翔（发起人）；D总（旁观）；小Q。林晓、周明、小周是材料里的人名。",
            "对应 BASE-STEER。10/19（周一）到 10/30 共 10 个工作日；周明 20–24 号出差，工作日里是 20–23 号。",
            "ask 派后台接单；fix 识别为纠正，一句确认；群里最后只有一份表，20–23 号没有周明；thanks 不回或一句。",
            "只有一份表且纠正生效、同一 Task，就通过。", "existing。", "预计通过或接近通过（Qwen-DWS 同构通过）。",
            "轮班名单换成东翔的组员，不再把上级 D总排进值班。")),
case(
    id="T-04", title="回放脚本跑着：别停 → 算了停了吧 → 停干净没 → 辛苦（BASE-STOP 真人版）",
    focus=["F5"], maps=["BASE-STOP"], scene="dm", conv="dm_zhujue", roles=RZ,
    steps=[
        say("start", "冬翔", "帮我在你那边跑下这个延迟数据回放脚本，大概四分钟，跑完把 P99 告诉我，我对一下昨天压测的数\nimport random, time\nrandom.seed(20261003)\nlat = []\nfor i in range(240):\n    time.sleep(1)\n    lat.append(random.gauss(118, 25))\nlat.sort()\nprint('P99=%.1f ms' % lat[int(len(lat) * 0.99)])",
            w_reply(120, 8), match_key="帮我在你那边跑下这个延迟数据回放脚本"),
        say("check", "冬翔", "跑上了没", w_reply(90, 10), match_key="跑上了没"),
        say("nostop", "冬翔", "跑着就行，别停啊，我就问问", w_opt(45, 15)),
        say("stop", "冬翔", "算了算了，停了吧，客户说今天先不对了", w_reply(120, 10), match_key="停了吧，客户说今天先不对了"),
        say("verify", "冬翔", "停干净了没？别一会儿又冒个结果出来", w_reply(120, 15)),
        say("thanks", "冬翔", "行 辛苦", w_sil(300)),
    ],
    criteria="否定句零控制；停止后真实退出才说停干净；越过原定结束时刻也没有 P99 数值，就通过。",
    checks=[
        chk("start", replies=[1, 1]), chk("check", replies=[1, 1], exc=[r"\d{1,3}\s*%"]), chk("nostop", replies=[0, 1]),
        noeff("check"), noeff("nostop"),
        chk("stop", replies=[1, 1]), chk("verify", replies=[1, 2]), noeff("verify"),
        chk(["start", "check", "nostop", "stop", "verify", "thanks"], exc=[r"P99\s*[=＝:：]\s*\d"]),
        chk("thanks", replies=[0, 1], maxc=20), noeff("thanks"), calls(3),
    ],
    pending_checks=[{"evidence": "effect_for_step", "step": "stop", "tools": ["stop_task"]},
                    {"evidence": "process_exit_confirmed", "step": "verify", "why": "第 5 步的说法要和真实退出状态一致"}],
    semantic=["「别停」没被当成停止", "停止回复不冒称已停干净", "「停干净没」的说法与 process_exit_confirmed 一致", "没补发旧结果，也没新开任务"],
    harness=[], ops=["routine_pause"], status="ready", reason="现有 harness 即可跑",
    doc=doc("东翔单聊。让员工跑一个四分钟的延迟数据回放脚本；先问跑上没、说一句「别停」，再真的要求停止，最后追问停干净没。",
            "冬翔/东翔；小Q。", "对应 BASE-STOP。脚本 240 秒，最后才打印 P99。",
            "start 派后台；check 实时读状态如实答；nostop 零控制，最多一句；stop 执行停止、回「已经让它停了」，不说已停干净；verify 按真实退出状态说；全程不出现 P99 数值；thanks 不回或一句。",
            "否定句零控制、停止诚实、无旧结果，就通过。", "existing。", "预计通过（Qwen-DWS 同构通过）。",
            "「压测脚本」改称「延迟数据回放脚本」，sleep + 随机数的写法对工程师不再显得假。")),
case(
    id="T-05", title="先出拜访统计，再「基于刚才这个」写复盘（builds_on：新工作建立在旧结果上）",
    focus=["F5", "F3"], maps=["G5-builds_on", "BASE-TASK"], scene="dm", conv="dm_zhujue", roles=RZ,
    steps=[
        say("visits", "冬翔", "9 月客户拜访记录我贴下面了，帮我按客户归一下：每家去了几次、最近一次哪天、谁去的。弄成表发我\n9/02 宏远 东翔 需求澄清\n9/05 中拓 D总 演示\n9/09 宏远 东翔+林晓 POC 启动\n9/12 安澜 D总 商务沟通\n9/16 宏远 林晓 POC 周会\n9/19 中拓 东翔 技术答疑\n9/23 安澜 D总 报价\n9/26 宏远 东翔 中期汇报\n9/29 中拓 D总 合同",
            w_reply(120, 8), match_key="9 月客户拜访记录我贴下面了"),
        obs("table", r"宏远[^\n]{0,30}4", since="visits", timeout=480),
        say("recap", "冬翔", "基于刚才这个统计，帮我写一页周会用的复盘，做成文档发我。三五句话就行，重点说下个月该往哪家多投人", w_reply(120, 8),
            match_key="基于刚才这个统计，帮我写一页周会用的复盘"),
        obs("recapdone", r"(宏远|中拓|安澜)[\s\S]{0,300}(投|人力|倾斜|重点)|\.(docx|md|pdf)", since="recap", timeout=480),
        say("thanks", "冬翔", "好 我周一用", w_sil(45)),
    ],
    criteria="统计 宏远4/9-26、中拓3/9-29、安澜2/9-23；复盘基于该结果（builds_on 新 Task），不回头要数据、不编，就通过。",
    checks=[
        chk("visits", replies=[2, 2], inc=["宏远", "中拓", "安澜"]),
        chk("recap", replies=[2, 2], exc=[r"哪个统计|把(数据|记录)(再)?(发|贴)"]),
        chk("thanks", replies=[0, 1], maxc=20), noeff("thanks"), calls(3),
        evx("tool_arg_present", step="recap", tool="dispatch_task", arg="builds_on", tier="target", requires="marker13"),
        evx("task_count", min=2, max=2, tier="target", requires="marker13"),
    ],
    semantic=["第二件事是引用第一件结果的新任务，不是对第一件的 continue", "没反问「哪个统计」，没要求重贴数据", "复盘数字与第一张表一致，没编拜访",
              "建议有依据（频次、阶段）"],
    harness=["grader_v2", "evidence_v2"], release=["marker13"], ops=["routine_pause"], status="ready_partial",
    reason="builds_on 参数未上预发（marker 13）；现在只能靠前台把结果抄进 prompt 碰巧通过", known_gap="G5 builds_on 未上预发",
    doc=doc("东翔单聊。先让员工把 9 月拜访记录按客户归类出表，再让它「基于刚才这个统计」写一页复盘。",
            "冬翔/东翔；小Q；D总、林晓（记录里的人名）。", "宏远 4 次（最近 9/26，东翔）；中拓 3 次（9/29，D总）；安澜 2 次（9/23，D总）。",
            "visits 出表；recap 新建任务并 builds_on 第一个任务，不 continue，不反问，复盘引用真实数字给投入建议；thanks 不回或一句。",
            "复盘基于真实结果、不回头要数据，就通过。", "wave2:G5（marker 13）。", "现在预计失败或部分失败；marker 13 上预发后预计通过。",
            "客户换成客户池，避免把核心客户华信写成「POC 启动」与世界设定冲突。")),
case(
    id="T-06", title="申领单「只要文件」→ 漏一条补上再发一版（BASE-FILE 真人版）",
    focus=["F5", "F3"], maps=["BASE-FILE"], scene="dm", conv="dm_director", roles=RD,
    steps=[
        say("ask", "D总", "10 月办公用品申领我汇总好了，帮我弄成 CSV 发我，只要文件，别再给我写一遍总结了\n行政部 A4纸 5箱\n行政部 签字笔 2盒\n研发部 白板笔 3盒\n研发部 HDMI转接头 4个\n销售部 名片 6盒",
            w_reply(180, 30), match_key="10 月办公用品申领我汇总好了"),
        obs("file1", r"\.csv", since="ask", timeout=480),
        say("add", "D总", "漏了一条：财务部 订书钉 3 盒，加上再发我一版", w_reply(180, 30), match_key="财务部 订书钉 3 盒"),
        obs("file2", r"\.csv", since="add", timeout=480),
        say("ok", "D总", "收到👌", w_sil(45), match_key="收到👌"),
    ],
    criteria="两次只发 CSV 不总结；第二版多「财务部,订书钉,3」；同一 Task 两个 Run，就通过。",
    checks=[
        chk("ask", replies=[2, 2], exc=[r"合计|共计|一共\s*\d|汇总如下|如下[:：]"]),
        chk("add", replies=[2, 2], exc=[r"合计|共计|一共\s*\d|汇总如下|如下[:：]"]),
        chk("ok", replies=[0, 1], maxc=20), noeff("ok"), runs(2), calls(3),
    ],
    pending_checks=[{"evidence": "file_download", "steps": ["file1", "file2"], "why": "下载两份文件核对 UTF-8、行数、hash，第二份含「财务部,订书钉,3」"}],
    semantic=["接单一句，不复述清单", "两份都是钉钉原生文件，不是正文贴表", "第二份继承只发文件，没补总结", "第二份多出订书钉一行"],
    harness=["file_download"], status="ready", reason="可跑；文件内容核对在 file_download（P1）前记 needs_review",
    doc=doc("D总单聊。行政采购：D总把申领汇总贴给员工，只要 CSV 文件、不要总结；随后补一行再要一版。",
            "D总；小Q。", "对应 BASE-FILE：completion_notice_policy=if_not_delivered，续接继承「只要文件」。",
            "ask 接单一句后只收到一个 CSV；add 续同一 Task，第二版 6 行；ok 不回或一句。", "两次只发文件、内容对、同一 Task，就通过。",
            "existing。", "Qwen-DWS 上已通过；Qwen-Real 若没装配钉钉文件工具会改成贴正文，判失败。",
            "「只要文件，别再给我写一遍总结了」是真人对啰嗦机器人的典型抱怨。")),
case(
    id="T-07", title="二十分钟的模拟跑批：停滞时如实提示一次，问「还要多久」不瞎报，插一个急问题照样秒答（WD-01/02）",
    focus=["F5"], maps=["WD-01", "WD-02"], scene="dm", conv="dm_director", roles=RD,
    steps=[
        say("run", "D总", "这个是回归的模拟跑批，慢，二十分钟左右，跑完把挂的用例名发我，不用盯着\nimport time\ncases = ['login', 'order', 'refund', 'invoice', 'export', 'audit']\nfailed = []\nfor c in cases:\n    time.sleep(200)\n    if c in ('refund', 'export'):\n        failed.append(c)\nprint('FAILED:', ', '.join(failed))",
            w_reply(120, 8), match_key="这个是回归的模拟跑批"),
        obs("stall", r"没有新的可观测输出|排队等待执行环境|无法回报进展|执行环境目前离线", since="run", timeout=900),
        say("howlong", "D总", "那大概还要多久？", w_reply(120, 10)),
        say("insert", "D总", "另外插个急的：宏远合同 37.5 万，按 3:4:3 分三期付，每期各多少？", w_reply(90, 10), match_key="按 3:4:3 分三期付"),
        obs("ans", r"11\.25\s*万|112,?500", since="insert", timeout=90),
        obs("result", r"refund[\s\S]{0,60}export|export[\s\S]{0,60}refund", since="run", timeout=1500),
        say("thanks", "D总", "好嘞 辛苦", w_sil(45)),
    ],
    criteria="停滞提示恰好一条且如实；问多久不编；插问当场答对且不影响原任务；结果 refund、export，就通过。",
    checks=[
        chk(["run", "howlong", "insert", "thanks"], replies=[5, 6], note="接单 + 停滞提示 + 多久 + 插问 + 结果（结果可能归到 thanks）"),
        chk(["run", "howlong", "insert", "thanks"], match_count={"regex": r"没有新的可观测输出", "range": [1, 1]}),
        chk("howlong", exc=[r"\d{1,3}\s*%", r"卡住"]), noeff("howlong"), noeff("insert"),
        chk("thanks", maxc=200), noeff("thanks"), calls(3),
    ],
    semantic=["停滞提示只有一条、如实，没有百分比、ETA 或「卡住」", "「还要多久」以实时状态和对方给的二十分钟为依据", "插问当场给出 11.25/15/11.25 万，没当成对跑批的纠正",
              "结果只发一次，refund 和 export 都在"],
    harness=["grader_v2", "config_snapshot"], ops=["watchdog_override", "deploy_freeze"], status="blocked",
    reason="需要在预发 Diamond 给 Qwen-Real 把 watchdog running 阈值调到 300s（运维动作需授权）；约 25 分钟窗口需部署冻结",
    doc=doc("D总单聊。D总在开会，顺手让员工跑一个约二十分钟、无中间输出的模拟跑批；中间问还要多久，又插问一个合同分期。",
            "D总；小Q。", "对应 WD-01/02。停滞提示是 Host 的确定性文案；问进展不算进展。插问：37.5 万按 3:4:3，每期 11.25 / 15 / 11.25 万。",
            "run 接单；到阈值 Host 发唯一一条停滞提示；howlong 实时读状态、以二十分钟为依据、不编；insert 当场答，不影响跑批；result 一次；thanks 不回或一句。",
            "提示一条且诚实、插问答对、结果对，就通过。", "existing（C1 停滞提示已随 marker 12）＋ 运维阈值覆盖。",
            "阈值覆盖前跑不了；覆盖后未知（执行器轮询输出可能被算作进展）。", "合同分期客户换成客户池宏远，不与华信 128 万的设定冲突。")),
case(
    id="T-08", title="群里定「每周五四点提醒更新客户台账」→ 这周先手动发一次 → 下周不用了删掉（CRON-01 手动运行分支）",
    focus=["F5", "F1"], maps=["CRON-01"], scene="group", conv="group_t", roles=RT,
    steps=[
        say("create", "D总", "以后每周五下午四点在群里提醒大家更新客户台账，就说：客户台账今天下班前更新，表在钉盘「客户台账/2026Q4」里",
            w_reply(120, 8), at=["employee"], match_key="以后每周五下午四点在群里提醒大家更新客户台账"),
        obs("created", r"例行任务「[^」]+」[\s\S]{0,120}(周五|星期五|16:00)", since="create", timeout=480),
        say("runnow", "D总", "这周的先手动发一次吧，我看看效果", w_reply(120, 8), at=["employee"], match_key="这周的先手动发一次吧"),
        obs("fired", r"例行任务「[^」]+」已完成", since="runnow", timeout=600),
        say("remove", "D总", "效果可以。不过下周起台账改用 AI 表格自动同步了，这个提醒先删了吧", w_reply(120, 8), at=["employee"], match_key="这个提醒先删了吧"),
        obs("removed", r"删除|已删|移除|删掉了", since="remove", timeout=480),
    ],
    criteria="建成周五 16:00 提醒；手动运行在群里真实发出含 2026Q4 的提醒；删除确认；无内部术语，就通过。",
    checks=[
        chk(["create", "created"], replies=[2, 2]),
        chk(["runnow", "fired"], replies=[2, 4], inc=["2026Q4"]),
        chk(["remove", "removed"], replies=[1, 3]),
        chk(["create", "runnow", "remove"], exc=[INTERNAL_RE, r"https?://\S*(webhook|hook)"]),
        calls(3),
    ],
    semantic=["新建确认是人话：周五 16:00、下次运行日期", "手动运行走了例行任务（平台开始/完成消息），员工没另发一遍提醒", "删除确认清楚", "全程无内部术语"],
    harness=["grader_v2"], status="ready", reason="group_t 不登记为例行任务会话，避免 grader 把平台消息当噪音",
    doc=doc("交付二组·项目推进群。D总让员工每周五提醒更新客户台账；这周先手动发一次看效果；随后说下周改自动同步，删掉。",
            "D总；冬翔/东翔（在群里）；小Q。", "例行任务的增删改和运行都经后台调用场域配置 MCP；立即运行时平台在群里依次发「开始执行…（手动运行）」和「…已完成」。",
            "create 用人话确认周五 16:00 与下次运行日；runnow 走立即运行，完成内容是那句提醒；remove 确认已删；不出现内部词或 Webhook 地址。",
            "建、跑、删都对且无内部词，就通过。", "existing。", "预计通过；风险是「手动发一次」被理解成直接在群里说一句。",
            "提醒内容改为客户台账，组内周报规矩只保留 G-15 一套，避免世界设定冲突。")),
case(
    id="T-09", title="发版下午：每 15 分钟提醒过灰度检查单 → 改文案 → 推迟暂停 → 恢复 → 发完删除（CRON-01/02/03，约 95 分钟）",
    focus=["F5"], maps=["CRON-01", "CRON-02", "CRON-03"], scene="group", conv="group_t", roles=RT, x_long_running=True,
    x_run_window={"from": "13:00", "to": "18:30", "why": "「今天下午发版…五点了」"},
    steps=[
        say("create", "冬翔", "今天下午发版，接下来每 15 分钟在群里提醒一下大家过一遍灰度检查单（钉盘「发版/灰度检查单-Q4」），等我说停再停",
            w_reply(120, 8), at=["employee"], match_key="接下来每 15 分钟在群里提醒一下大家过一遍灰度检查单"),
        obs("created", r"例行任务「[^」]+」", since="create", timeout=480),
        obs("due1", r"开始执行例行任务「[^」]+」（定时触发", since="create", timeout=1080),
        obs("end1", r"例行任务「[^」]+」已完成", since="create", timeout=600),
        say("edit", "冬翔", "提醒里加一句：有异常直接 @我，别在群里干等", w_reply(120, 8), at=["employee"], match_key="提醒里加一句：有异常直接"),
        obs("edited", r"已更新|已修改|改好|更新了", since="edit", timeout=480),
        obs("due2", r"已完成[\s\S]{0,400}(异常|东翔|冬翔)", since="edit", timeout=1200),
        say("pause", "冬翔", "发版推迟到五点了，提醒先停一下，别删", w_sil(1080), at=["employee"], match_key="提醒先停一下，别删"),
        say("resume", "冬翔", "好了 五点了，接着提醒吧", w_reply(120, 8), at=["employee"], match_key="五点了，接着提醒吧"),
        obs("due3", r"开始执行例行任务「[^」]+」（定时触发", since="resume", timeout=1080),
        say("stop", "冬翔", "发完了，提醒删了吧，辛苦", w_reply(120, 8), at=["employee"], match_key="发完了，提醒删了吧"),
        obs("stopped", r"删除|已删|移除|删掉了", since="stop", timeout=480),
    ],
    criteria="真实到点执行；改文案从下一次生效；暂停期间零执行、恢复后按时执行；删除后不再触发，就通过。",
    checks=[
        chk("pause", exc=[r"开始执行例行任务"]),
        chk(["create", "edit", "pause", "resume", "stop"], exc=[INTERNAL_RE, r"\*/15|cron"]),
        calls(3),
    ],
    pending_checks=[{"evidence": "negative_observe", "between": ["pause", "resume"], "regex": r"开始执行例行任务", "count": 0},
                    {"evidence": "pg_occurrence", "why": "核对 occurrence 的 planned_at 与 skipped 原因"}],
    semantic=["新建确认含下次运行时间", "due1 用旧文案，due2 起带「有异常直接找东翔」", "暂停期间越过计划时点零执行", "恢复后下一合法时点执行", "删除后不再触发"],
    harness=["grader_v2", "negative_observe", "segments", "pg_read"], ops=["deploy_freeze"], status="blocked",
    reason="约 95 分钟窗口几乎必撞部署，需在部署冻结窗口跑或按段判有效性；暂停段要负向观察",
    doc=doc("交付二组·项目推进群。发版日下午，东翔让员工每 15 分钟提醒一次，中途改文案、推迟暂停、恢复、发完删除。",
            "冬翔/东翔（发版负责人）；D总（旁观）；小Q。", "对应 CRON-01/02/03。系统最小间隔 15 分钟。开始消息形如「开始执行例行任务「…」（定时触发 · 计划 HH:MM）」。",
            "建出每 15 分钟一次；到点平台发开始与完成；改文案只影响之后；暂停期间零执行；恢复后下一时点执行；删除后不再触发；员工回复都是人话。",
            "到点、改文案、暂停恢复、删除都对，就通过。", "existing。", "代码层面预计通过；实际跑基本会因部署判 invalid_env。",
            "唯一刻意设计的长时 case；全程只靠平台固定文案观察，没有可见标记。")),
case(
    id="T-10", title="条件型例行任务：每 15 分钟看一眼问题登记表，有新登记才吭声（CRON-04 decision）",
    focus=["F5", "F1"], maps=["CRON-04"], scene="group", conv="group_t", roles=RT,
    steps=[
        say("create", "冬翔", "发版这两个小时，每 15 分钟帮我看一眼「Q4发版问题登记」那张表，有新登记的问题就在群里说一声是谁登的、啥问题，没有新的就别吭声",
            w_reply(120, 8), at=["employee"], match_key="每 15 分钟帮我看一眼「Q4发版问题登记」那张表"),
        obs("created", r"例行任务「[^」]+」", since="create", timeout=480),
        say("quiet", "D总", "表我建好了，现在是空的，大家有问题往里登", w_sil(1080), match_key="表我建好了，现在是空的"),
        act("inject", "aitable_insert", "D总", table="Q4发版问题登记", record={"问题": "订单导出超时，偶发 504", "登记人": "D总"}),
        say("mention", "D总", "我在表里登了个导出超时的", w_none(3)),
        obs("hit", r"导出超时", since="mention", timeout=1080),
        say("remove", "冬翔", "发完了，这个检查也撤了吧", w_reply(120, 8), at=["employee"], match_key="这个检查也撤了吧"),
        obs("removed", r"删除|已删|撤了|移除", since="remove", timeout=480),
    ],
    criteria="空表那次零消息；新登记那次恰好一条且含登记人与问题；删除确认，就通过。",
    checks=[
        chk("quiet", replies=[0, 0]),
        chk(["create", "remove"], exc=[INTERNAL_RE]),
        calls(3),
    ],
    pending_checks=[{"evidence": "per_occurrence_calls", "max": 3}],
    semantic=["条件不满足时完全安静（不发开始/结束噪音、不说「暂无新问题」）", "条件满足时一条消息，写清谁登记了什么", "不重复报已报过的行"],
    harness=["aitable_insert", "grader_v2", "pg_read"], release=["B3_decision"], status="blocked",
    reason="decision 模式（B3）未交付；harness 缺写表步骤",
    doc=doc("交付二组·项目推进群。东翔让员工发版期间每 15 分钟看一眼问题登记表，有新登记才说话；D总中途往表里登记一条。",
            "冬翔/东翔；D总；小Q。", "需事先建好 AI 表格并授权员工后台可读。对应 CRON-04。",
            "空表那次完全安静；新登记那次一条，写明 D总登记了导出超时；删除确认一次。", "安静与说话都对，就通过。",
            "wave2:B3（decision）。", "现在跑不了：run_only 每次都会发开始/结束消息。",
            "「有就说，没有别吭声」是群里对机器人最常见的要求。")),
case(
    id="T-11", title="CI 挂了自动在群里通报：Webhook 例行任务（合法 / 重投 / 改内容 / 错签 / 绿灯安静）（HOOK-01..04）",
    focus=["F5"], maps=["HOOK-01", "HOOK-02", "HOOK-03", "HOOK-04"], scene="group", conv="group_t", roles=RT,
    steps=[
        say("create", "D总", "以后咱们 huaxin-api 的流水线挂了，让它通过 webhook 自动在群里通报一下：哪个阶段挂的、最近一次提交是谁的。绿的就别发了",
            w_reply(120, 8), at=["employee"], match_key="huaxin-api 的流水线挂了"),
        obs("created", r"Webhook|配置页", since="create", timeout=480),
        act("hook1", "webhook", None, delivery_id="ci-1003-0412",
            body={"pipeline": "huaxin-api", "status": "failed", "stage": "集成测试", "commit": "8c3991a", "author": "周明"}, expect_http=200),
        obs("fired", r"（Webhook 触发）", since="create", timeout=300),
        obs("report", r"集成测试", since="create", timeout=480),
        act("dup", "webhook", None, delivery_id="ci-1003-0412",
            body={"pipeline": "huaxin-api", "status": "failed", "stage": "集成测试", "commit": "8c3991a", "author": "周明"}, expect_http=[200, 202, 409], quiet_window_s=120),
        act("conflict", "webhook", None, delivery_id="ci-1003-0412",
            body={"pipeline": "huaxin-api", "status": "failed", "stage": "部署", "commit": "8c3991a", "author": "周明"}, expect_http=409, quiet_window_s=120),
        act("badsig", "webhook", None, delivery_id="ci-1003-0419",
            body={"pipeline": "huaxin-api", "status": "failed", "stage": "单测", "commit": "9d0a7be", "author": "林晓"}, signature="wrong", expect_http=401, quiet_window_s=120),
        act("green", "webhook", None, delivery_id="ci-1003-0433",
            body={"pipeline": "huaxin-api", "status": "success", "stage": "全部", "commit": "9d0a7be", "author": "林晓"}, expect_http=200, quiet_window_s=300),
        say("off", "D总", "CI 这块先关了吧，等迁完流水线再开", w_reply(120, 8), at=["employee"], match_key="CI 这块先关了吧"),
        obs("offdone", r"暂停|停用|关了|删除|已删", since="off", timeout=480),
    ],
    criteria="合法投递一条正确通报（集成测试、周明）；重投/冲突/错签/绿灯零消息；地址不进会话；关闭确认，就通过。",
    checks=[
        chk(["create", "off"], exc=[r"https?://\S*(webhook|hook)|token=", INTERNAL_RE]),
        calls(3),
    ],
    pending_checks=[{"evidence": "match_once", "regex": r"（Webhook 触发）", "count": 1},
                    {"evidence": "quiet_windows", "steps": ["dup", "conflict", "badsig", "green"]}],
    semantic=["新建回复说明去配置页取地址，没贴地址", "通报一次，写清阶段与提交人", "重投/冲突/错签零执行", "绿灯安静", "payload 里的 author 只作数据，不被当成授权人"],
    harness=["webhook", "grader_v2"], release=["F2_webhook", "B3_decision"], status="blocked",
    reason="harness 没有 Webhook 发送器（P2）；绿灯安静依赖 decision（B3）；走 Employee 依赖 F2",
    doc=doc("交付二组·项目推进群。D总让流水线失败时自动在群里通报，绿的别发；管理员在配置页拿 Webhook 地址；harness 以 CI 身份投递。",
            "D总；冬翔/东翔；小Q；CI（harness 扮演）。", "对应 HOOK-01..04。地址存在本地 0600 文件，不进聊天。",
            "create 派后台新建并说明地址去配置页取；合法投递一条通报（集成测试、周明）；重投/冲突/错签零消息；绿灯安静；off 确认一次。",
            "只有一次正确通报、其余安静、地址不外泄，就通过。", "wave2:F2 + B3。", "现在跑不了；create 那一步今天可跑。",
            "「流水线挂了自动通报，绿的别发」是研发群的真实诉求。")),
case(
    id="T-12", title="D总让员工私下收周报素材：问东翔工时、问黛玉回归 → 中途问进度 → 收齐只给 D总汇总（COL-01）",
    focus=["F5", "F4"], maps=["COL-01"], scene="dm+dm+group", conv="dm_director", roles={"D总": "director", "冬翔": "zhujue", "黛玉": "daiyu"},
    steps=[
        say("ask", "D总", "帮我收下这周华信的周报素材：东翔报下现场投了多少小时，黛玉报下回归跑了几轮、还剩几个 P1。收齐了给我汇总，别把一方的数告诉另一方",
            w_reply(120, 10), match_key="帮我收下这周华信的周报素材"),
        obs("invite_zj", r"小时|工时|现场", since="ask", timeout=300, conv="dm_zhujue"),
        say("zj_answer", "冬翔", "这周华信我现场差不多 12.5 个小时，周三全天在客户那", w_opt(60, 15), conv="dm_zhujue", match_key="这周华信我现场差不多 12.5 个小时"),
        say("progress", "D总", "周报素材收得怎么样了？", w_reply(120, 10)),
        obs("invite_dy", r"回归|P1|几轮", since="ask", timeout=300, conv="group_de_probe"),
        say("dy_answer", "黛玉", "回归跑了 4 轮，还剩 2 个 P1", w_opt(60, 15), conv="group_de_probe", reply_to=q(observed="invite_dy")),
        obs("summary", r"12\.5[\s\S]{0,200}(4\s*轮|2\s*个\s*P1)|(4\s*轮|2\s*个\s*P1)[\s\S]{0,200}12\.5", since="progress", timeout=300),
        say("thanks", "D总", "好 谢了", w_sil(45)),
    ],
    criteria="进度确切 1/2（东翔 12.5 小时已回）；一次汇总含两方数据；参与者互不可见对方的数，就通过。",
    checks=[
        chk("ask", replies=[1, 1]),
        chk("progress", replies=[1, 1], inc=["12.5"]),
        sent("4 轮", "dm_zhujue"), sent("2 个 P1", "dm_zhujue"), sent("12.5", "group_de_probe"),
        chk("thanks", replies=[0, 1], maxc=20), noeff("thanks"), calls(3),
    ],
    pending_checks=[{"evidence": "pg_collection", "why": "collection/invitation/input 计数、一次原场域汇总"}],
    semantic=["邀请措辞自然、每人一次", "进度是确切的 1/2，没编", "汇总只发一次到原场域，两方数据都在", "参与者看不到彼此的数",
              "如果黛玉无法私聊（DE↔DE），员工在 group_de_probe 问她，或如实告诉 D总，不偷偷在别的群公开问"],
    harness=["quote_reply", "deap_multi", "grader_v2", "pg_read"], release=["marker13"], status="blocked",
    reason="跨场域收集（A2，marker 13）未上预发；黛玉是 DEAP，邀请落点按本题约定在 group_de_probe",
    doc=doc("D总单聊。D总让员工私下收这周华信的周报素材：东翔的现场工时、黛玉的回归进度；中途问进度；收齐后只给 D总汇总。",
            "D总（发起）；冬翔/东翔（真人参与者，在自己单聊答）；黛玉（DEAP 测试数字员工，在 EL-E2E-1003-DE 群里引用邀请作答）；小Q。",
            "对应 COL-01，顺带测隐私：参与者互相看不到对方的数，只有发起人看到汇总。数字员工之间没有私聊场域，黛玉的邀请落点约定在 group_de_probe。",
            "ask 接单一句；邀请自然、每人一次；progress 确切 1/2（东翔 12.5 小时已回，还差黛玉）；黛玉答后原场域一次汇总；各参与者场域里看不到对方的数。",
            "进度确切、汇总一次、互不可见，就通过。", "wave2:A2（marker 13）。", "blocked。",
            "收「工时」改成收周报素材：工时问真人东翔，回归进度问测试数字员工黛玉，不再让数字员工报工时。")),
case(
    id="T-13", title="预授权三步走：工时按项目汇总 → 算占比 → 写结论，中间不用问（FOLLOW-01）",
    focus=["F5"], maps=["FOLLOW-01"], scene="dm", conv="dm_zhujue", roles=RZ,
    steps=[
        say("plan", "冬翔", "帮我分三步弄下 9 月工时：第一步把下面的记录按项目汇总；汇总完接着算各项目人力占比；最后写两三句结论发我。一步做完直接接下一步，中间不用问我\n林晓 华信 62\n林晓 睿博 18\n周明 华信 40\n周明 启明 36\n东翔 华信 50\n东翔 睿博 30\nD总 启明 24\nD总 睿博 20",
            w_reply(120, 8), match_key="帮我分三步弄下 9 月工时"),
        obs("s1", r"152", since="plan", timeout=480),
        obs("s2", r"54\.3\s*%", since="plan", timeout=600),
        obs("s3", r"(华信)[\s\S]{0,120}(过半|一半以上|超过一半|重心|主力|最多)", since="plan", timeout=600),
        say("thanks", "冬翔", "好 辛苦", w_sil(45)),
    ],
    criteria="同一 Task 三个 Run 自动推进；152/68/60；54.3/24.3/21.4%；结论有依据；中途不问人，就通过。",
    checks=[
        chk(["plan", "thanks"], replies=[4, 5], inc=["152", "68", "60"], exc=[r"要(我)?继续吗|需要继续吗|是否继续"]),
        chk("thanks", maxc=200), noeff("thanks"), calls(3),
        runs(3, tier="target"),
        evx("tool_arg_present", step="plan", tool="dispatch_task", arg="follow_up_steps", tier="target", requires="marker13"),
    ],
    semantic=["按预授权自动接下一步，没中途问人", "每步结果各一次、数字正确", "结论基于占比，没额外编造", "没多出第 4 步"],
    harness=["grader_v2", "evidence_v2"], release=["marker13"], ops=["routine_pause"], status="ready_partial",
    reason="follow_up_steps 未上预发（marker 13）；现在员工可能一次做完三步（结果对但 Run 数不对）", known_gap="P3 follow_up_steps 未上预发",
    doc=doc("东翔单聊。东翔要分三步处理 9 月工时，并明确预授权「一步做完直接接下一步」。",
            "冬翔/东翔；小Q。", "对应 FOLLOW-01：同一 Task，后一步由 Host 确定性派发。华信 152、睿博 68、启明 60；占比 54.3% / 24.3% / 21.4%。",
            "接单说明会三步依次做完；同一 Task 依次 3 个 Run，每步结果各一次；不反复问要不要继续；thanks 不回或一句。",
            "三步自动推进、数字对，就通过。", "wave2:P3（marker 13）。", "现在预计 Run 数不对；一次做完三步的语义是否可接受需冬翔定口径。",
            "「分三步」「中间不用问我」是真人授权多步工作的说法。")),
case(
    id="T-14", title="两件模拟在跑，「那个先停了吧」→ 先问是哪个 → 「对账那个」→ 只停对账，导出照常出",
    focus=["F5", "F3"], maps=["BASE-STOP", "REF-01"], scene="dm", conv="dm_zhujue", roles=RZ,
    steps=[
        say("a", "冬翔", "帮我跑下这个对账模拟，三分钟左右：\nimport time\ntime.sleep(180)\nprint('对账差异 3 笔：A1029、A1047、A1102')", w_reply(120, 8), match_key="帮我跑下这个对账模拟"),
        say("b", "冬翔", "还有这个导出模拟也跑一下，俩不冲突：\nimport time\ntime.sleep(200)\nprint('导出完成，共 1286 行')", w_reply(120, 8), match_key="还有这个导出模拟也跑一下"),
        say("vague", "冬翔", "那个先停了吧", w_reply(90, 10), match_key="那个先停了吧"),
        say("which", "冬翔", "对账那个，数据源换了，跑了也白跑", w_reply(120, 10)),
        obs("exported", r"1,?286", since="b", timeout=600),
        say("thanks", "冬翔", "导出的收到了，谢谢", w_sil(120)),
    ],
    criteria="「那个」先澄清不动手；只停对账；导出照常一次；对账单号从未出现，就通过。",
    checks=[
        chk("vague", replies=[1, 1]), noeff("vague"), chk("which", replies=[1, 1]),
        chk(["a", "b", "vague", "which", "thanks"], exc=[r"A1029|A1047|A1102"]),
        chk(["b", "which", "thanks"], inc=["1286"]),
        chk("thanks", maxc=120), calls(3),
    ],
    pending_checks=[{"evidence": "effect_for_step", "step": "which", "tools": ["stop_task"], "target_task": "a"}],
    semantic=["「那个」被识别为有歧义，用一句话反问", "只停对账，导出不受影响", "停止回复不冒称已停干净", "导出结果只发一次"],
    harness=[], ops=["routine_pause"], status="ready", reason="现有 harness 即可跑",
    doc=doc("东翔单聊。一口气让员工跑两个模拟脚本，随后说「那个先停了吧」，再指明是对账那个。",
            "冬翔/东翔；小Q。", "合同：多个可能事项时先澄清，不能把最近一个当成当前事项。对账 180 秒，导出 200 秒。",
            "vague 不动手，一句反问；which 只停对账，不说已停干净；导出照常完成、只发一次；对账单号永不出现；thanks 不回或一句。",
            "澄清、精确停止、导出正常，就通过。", "existing。", "可能通过；风险是直接停最近的导出，或两任务串行导致导出更晚（超时已放到 600 秒）。",
            "脚本称「模拟」，不再假装是真对账、真导出。")),
case(
    id="T-15", title="引用比价表「这个再加一列」续接；D总引用指出数错了，员工不擅改、等东翔拍板（REF-01）",
    focus=["F5", "F4", "F2"], maps=["REF-01"], scene="group", conv="group_t", roles=RT,
    steps=[
        say("ask", "冬翔", "把这三家供应商的报价按总价从低到高排一下（软件+实施+一年维保算总价），列个表发群里，周一跟采购过\n云图：软件 18 万，实施 9.5 万，年维保 3 万\n数衡：软件 22 万，实施 8 万，年维保 2.5 万\n北辰：软件 16 万，实施 12 万，年维保 4 万",
            w_reply(120, 8), at=["employee"], match_key="把这三家供应商的报价按总价从低到高排一下"),
        obs("r1", r"30\.5", since="ask", timeout=480),
        say("more", "冬翔", "这个再加一列，按三年维保算的总价", w_reply(120, 8), reply_to=q(observed="r1"), match_key="这个再加一列，按三年维保算的总价"),
        obs("r2", r"36\.5[\s\S]{0,300}40|40[\s\S]{0,300}36\.5", since="more", timeout=480),
        say("dfix", "D总", "数衡实施费是 8.8 万，不是 8 万，你这写错了", w_reply(120, 10), reply_to=q(observed="r2"), match_key="数衡实施费是 8.8 万"),
        say("zconfirm", "冬翔", "对，以 D总说的为准，改一下", w_reply(120, 8), at=["employee"], match_key="以 D总说的为准"),
        obs("r3", r"38\.3", since="zconfirm", timeout=480),
        say("thanks", "冬翔", "行 周一就用这版", w_sil(60), at=["employee"]),
    ],
    criteria="引用续接同一 Task；D总指错时不擅改、请东翔确认；东翔确认后 33.3/38.3，就通过。",
    checks=[
        chk("ask", replies=[2, 2]), chk("more", replies=[2, 2]),
        chk("dfix", replies=[1, 1], exc=[r"已(经)?(改|更新|修改)"]), noeff("dfix"),
        chk("zconfirm", replies=[2, 2]),
        chk("thanks", replies=[0, 1], maxc=30), noeff("thanks"), runs(3), calls(3),
    ],
    semantic=["「这个再加一列」理解为同一张表的续接", "D总指错时说明数是东翔给的并 @东翔 确认，没擅改", "东翔确认后改对、排序复核", "群里没有两版矛盾又不说明的表"],
    harness=["quote_reply", "grader_v2"], status="ready", reason="引用续接靠模型对上候选事项；确定性定位（D3）在第二波",
    doc=doc("交付二组·项目推进群。东翔要三家供应商比价表；引用结果要再加一列；D总引用新结果指出一个数错了；东翔确认后再改。",
            "冬翔/东翔（选型负责人）；D总（指错的人，不是这件事的请求者）；小Q。",
            "首年总价 云图 30.5 < 北辰 32 < 数衡 32.5；三年 36.5 / 40 / 37.5；数衡实施改 8.8 后首年 33.3、三年 38.3。D总不是请求者，不能直接纠正东翔的任务。",
            "ask 派后台按首年排序；more 同一 Task 新 Run；dfix 不擅改，说明 8 万是东翔给的，@东翔 确认；zconfirm 后改对；thanks 不回或一句。",
            "续接不另建、他人指错不擅改、确认后改对，就通过。", "existing ＋ wave2:D3（引用确定性定位）。",
            "harness 侧需引用回复；产品侧未知：D总指错这一步可能被派成 D总自己的新任务。",
            "比价对象从核心客户（华信、睿博、启明）改为供应商，避免把客户写成报价方；题面写明总价口径。")),
case(
    id="T-16", title="先贴会议结论，过一会儿「按刚才的结论出个准备清单」（办事要带上前文）",
    focus=["F5", "F3"], maps=["BASE-TASK", "G3"], scene="dm", conv="dm_director", roles=RD,
    steps=[
        say("notes", "D总", "刚开完会，结论贴你这：\n1. 睿博演示定在 10/14 下午两点，他们 CTO 会来\n2. 演示脚本用东翔那版，东翔 10/12 前再过一遍\n3. 物料我来弄：宣传册 30 份、样机 2 台，10/13 前到位\n4. 场地还没定，林晓 10/9 前问行政\n5. 会后要给陈总发会议纪要，10/15 前",
            w_opt(60, 15), match_key="刚开完会，结论贴你这"),
        say("make", "D总", "按刚才的会议结论帮我出个演示准备清单，每项带负责人和截止日期，排好版直接发我，我贴到站会文档里", w_reply(180, 20),
            match_key="按刚才的会议结论帮我出个演示准备清单"),
        obs("list", r"^(?=[\s\S]*林晓)(?=[\s\S]*东翔)(?=[\s\S]*宣传册)", since="make", timeout=480),
        say("thanks", "D总", "可以 谢谢", w_sil(45)),
    ],
    criteria="五项齐全、负责人和日期与结论一致；纪要负责人标待定不编；不回头要材料，就通过。",
    checks=[
        chk("notes", replies=[0, 1], maxc=120),
        chk(["make", "thanks"], inc=["东翔", "林晓", "宣传册"], exc=[r"负责人[:：]?\s*陈总", r"哪个会|什么会议|请把会议"]),
        chk("thanks", maxc=200), noeff("thanks"), calls(3),
    ],
    pending_checks=[{"evidence": "tool_arg_contains", "step": "make", "tool": "dispatch_task", "arg": "prompt",
                     "values": ["10/14", "10/12", "宣传册", "林晓", "10/15"], "if_dispatched": True}],
    semantic=["收到会议结论时简短回应", "清单五项齐全，负责人和日期准确", "纪要负责人标待定，没把陈总写成负责人", "若派后台，prompt 带全五条，执行器没回头问"],
    harness=[], status="ready", reason="现有 harness 即可跑",
    doc=doc("D总单聊。刚开完睿博演示的准备会，D总把结论贴过来；过一会儿再让员工按结论出准备清单。",
            "D总；小Q；东翔、林晓（结论里的负责人）；陈总（睿博，纪要收件人）。",
            "派后台时执行器工作包历史显示 unavailable（缺口 G3），前台必须把五条写进 prompt；前台直接回复也可以。",
            "notes 简短回应；make 五项：脚本—东翔—10/12；物料—D总—10/13；场地—林晓—10/9；演示 10/14 14:00；纪要—负责人待定—10/15。不漏不编。",
            "五项齐全、不编负责人、不回头要材料，就通过。", "existing；wave2:G3 会更稳。", "大概率通过；纪要负责人编造是独立风险点。",
            "演示改为睿博（核心客户里在走合同的那家），纪要发陈总，与世界设定一致。")),
]
