// Verbatim declarations copied from github.com/DingTalk-Real-AI/dingtalk-workspace-cli
// tag v1.0.62-beta.8 (Apache-2.0; see clicompat/NOTICE). Generated by
// clicompat_excerpts.py: each declaration, doc comment included, is byte for
// byte the dws source at the file and line listed; nothing else is in this
// file except the package clause and imports.
//
//	type CommandResult                           internal/output/result.go:19
//	type commandResult                           internal/output/result.go:25
//	method commandResult.Outcome                 internal/output/result.go:31
//	method commandResult.ExitCode                internal/output/result.go:32
//	method commandResult.envelope                internal/output/result.go:33
//	type ResultOption                            internal/output/result.go:39
//	func Success                                 internal/output/result.go:54
//	func Pending                                 internal/output/result.go:59
//	func FailureWithExitCode                     internal/output/result.go:89
//	func newCommandResult                        internal/output/result.go:97
//	func newCommandResultWithExitCode            internal/output/result.go:101
//	func cloneEnvelope                           internal/output/result.go:120
//	func cloneMeta                               internal/output/result.go:146
//	func cloneResultData                         internal/output/result.go:166
//	type cloneVisit                              internal/output/result.go:173
//	func cloneReflectValue                       internal/output/result.go:180
//	func cloneErrorInfo                          internal/output/result.go:254
//	func ValidateResult                          internal/output/result.go:279
//	func EnvelopeFromResult                      internal/output/result.go:472
//	const exitCodeOK                             internal/output/emitter.go:451
//	const subtypeConfirmationRequired            internal/output/emitter.go:464
//	func ExitCodeForEnvelope                     internal/output/emitter.go:478
//	func exitCodeForErrorInfo                    internal/output/emitter.go:498
//	func toGeneric                               internal/output/filter.go:216
//	var marshalJSON                              internal/output/formatter.go:61
//	func unmarshalJSONUseNumber                  internal/output/formatter.go:68
//	func normalizeSafeJSONNumbers                internal/output/formatter.go:84
//	func WriteJSON                               internal/output/formatter.go:385
//
// internal/output is vendored only partly (envelope.go, redaction.go): its other
// files import cobra or gojq. These are the declarations of those files that
// envelope.go, redaction.go and clicompat need.

package output

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
	"strconv"
	"strings"

	apperrors "github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/errors"
	"github.com/multica-ai/multica/server/pkg/dws/clicompat/internal/upstream/jsonutil"
)

// CommandResult is the immutable framework result consumed by CLI and MCP
// adapters. The unexported envelope method prevents product packages from
// implementing ad-hoc result shapes.
type CommandResult interface {
	Outcome() Outcome
	ExitCode() int
	envelope() *Envelope
}

type commandResult struct {
	env              Envelope
	exitCode         int
	exitCodeOverride bool
}

func (r *commandResult) Outcome() Outcome { return r.env.Outcome }
func (r *commandResult) ExitCode() int    { return r.exitCode }
func (r *commandResult) envelope() *Envelope {
	copy := cloneEnvelope(r.env)
	return &copy
}

// ResultOption enriches a result without exposing mutable framework fields.
type ResultOption struct{ apply func(*Envelope) }

// Success constructs an immutable success result.
func Success(data any, opts ...ResultOption) CommandResult {
	return newCommandResult(OutcomeSuccess, data, nil, opts...)
}

// Pending constructs an immutable accepted-but-not-terminal result.
func Pending(data any, operation *OperationInfo, opts ...ResultOption) CommandResult {
	opts = append(opts, ResultOption{apply: func(env *Envelope) {
		if env.Meta == nil {
			env.Meta = &Meta{}
		}
		env.Meta.Operation = operation
	}})
	return newCommandResult(OutcomePending, data, nil, opts...)
}

// FailureWithExitCode adapts an existing repository error whose historical
// process status is part of a compatibility contract (for example SIGINT=130).
// Product handlers must use Failure; only the root legacy-error adapter should
// call this function.
func FailureWithExitCode(info *ErrorInfo, exitCode int, opts ...ResultOption) CommandResult {
	if info != nil {
		info = cloneErrorInfo(info)
		info.ExitCode = 0
	}
	return newCommandResultWithExitCode(OutcomeFailure, nil, info, exitCode, true, opts...)
}

func newCommandResult(outcome Outcome, data any, info *ErrorInfo, opts ...ResultOption) CommandResult {
	return newCommandResultWithExitCode(outcome, data, info, 0, false, opts...)
}

func newCommandResultWithExitCode(outcome Outcome, data any, info *ErrorInfo, override int, hasOverride bool, opts ...ResultOption) CommandResult {
	env := Envelope{Outcome: outcome, Data: data, Error: info}
	env.OK = outcome == OutcomeSuccess || outcome == OutcomePending
	for _, opt := range opts {
		if opt.apply != nil {
			opt.apply(&env)
		}
	}
	exitCode := ExitCodeForEnvelope(&env)
	if hasOverride && override > 0 {
		exitCode = override
	}
	if env.Error != nil {
		env.Error.ExitCode = exitCode
	}
	env = cloneEnvelope(env)
	return &commandResult{env: env, exitCode: exitCode, exitCodeOverride: hasOverride}
}

func cloneEnvelope(source Envelope) Envelope {
	out := source
	out.Meta = cloneMeta(source.Meta)
	out.Error = cloneErrorInfo(source.Error)
	out.Data = cloneResultData(source.Data)
	out.Notice = cloneResultData(source.Notice)
	if partial, ok := source.Data.(*PartialData); ok && partial != nil {
		copyPartial := &PartialData{
			Total:     partial.Total,
			Succeeded: make([]any, len(partial.Succeeded)),
			Failed:    make([]PartialFailedEntry, len(partial.Failed)),
			Unknown:   make([]PartialUnknownEntry, len(partial.Unknown)),
		}
		copy(copyPartial.Failed, partial.Failed)
		copy(copyPartial.Unknown, partial.Unknown)
		for i := range partial.Succeeded {
			copyPartial.Succeeded[i] = cloneResultData(partial.Succeeded[i])
		}
		for i := range copyPartial.Failed {
			copyPartial.Failed[i].Error = cloneErrorInfo(copyPartial.Failed[i].Error)
		}
		out.Data = copyPartial
	}
	return out
}

func cloneMeta(source *Meta) *Meta {
	if source == nil {
		return nil
	}
	meta := *source
	if source.Count != nil {
		count := *source.Count
		meta.Count = &count
	}
	if source.Operation != nil {
		op := *source.Operation
		meta.Operation = &op
	}
	if source.Pagination != nil {
		pagination := *source.Pagination
		meta.Pagination = &pagination
	}
	return &meta
}

func cloneResultData(value any) any {
	if value == nil {
		return nil
	}
	return cloneReflectValue(reflect.ValueOf(value), make(map[cloneVisit]reflect.Value)).Interface()
}

type cloneVisit struct {
	typ reflect.Type
	ptr uintptr
	len int
	cap int
}

func cloneReflectValue(value reflect.Value, seen map[cloneVisit]reflect.Value) reflect.Value {
	if !value.IsValid() {
		return value
	}
	switch value.Kind() {
	case reflect.Interface:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		cloned := cloneReflectValue(value.Elem(), seen)
		out := reflect.New(value.Type()).Elem()
		out.Set(cloned)
		return out
	case reflect.Pointer:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		visit := cloneVisit{typ: value.Type(), ptr: value.Pointer()}
		if cloned, ok := seen[visit]; ok {
			return cloned
		}
		out := reflect.New(value.Type().Elem())
		seen[visit] = out
		out.Elem().Set(cloneReflectValue(value.Elem(), seen))
		return out
	case reflect.Map:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		visit := cloneVisit{typ: value.Type(), ptr: value.Pointer()}
		if cloned, ok := seen[visit]; ok {
			return cloned
		}
		out := reflect.MakeMapWithSize(value.Type(), value.Len())
		seen[visit] = out
		iter := value.MapRange()
		for iter.Next() {
			out.SetMapIndex(cloneReflectValue(iter.Key(), seen), cloneReflectValue(iter.Value(), seen))
		}
		return out
	case reflect.Slice:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		visit := cloneVisit{typ: value.Type(), ptr: value.Pointer(), len: value.Len(), cap: value.Cap()}
		if cloned, ok := seen[visit]; ok {
			return cloned
		}
		out := reflect.MakeSlice(value.Type(), value.Len(), value.Len())
		seen[visit] = out
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(cloneReflectValue(value.Index(i), seen))
		}
		return out
	case reflect.Array:
		out := reflect.New(value.Type()).Elem()
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(cloneReflectValue(value.Index(i), seen))
		}
		return out
	case reflect.Struct:
		out := reflect.New(value.Type()).Elem()
		out.Set(value)
		for i := 0; i < value.NumField(); i++ {
			if value.Type().Field(i).PkgPath == "" && out.Field(i).CanSet() {
				out.Field(i).Set(cloneReflectValue(value.Field(i), seen))
			}
		}
		return out
	default:
		return value
	}
}

func cloneErrorInfo(source *ErrorInfo) *ErrorInfo {
	if source == nil {
		return nil
	}
	out := *source
	out.UpstreamCode = cloneResultData(source.UpstreamCode)
	out.Params = append([]string(nil), source.Params...)
	out.Actions = append([]string(nil), source.Actions...)
	out.AvailableFlags = append([]string(nil), source.AvailableFlags...)
	if source.ExecutionStarted != nil {
		started := *source.ExecutionStarted
		out.ExecutionStarted = &started
	}
	if source.Details != nil {
		out.Details = cloneResultData(source.Details).(map[string]any)
	}
	out.RPCData = cloneResultData(source.RPCData)
	if source.RetryAfterSeconds != nil {
		seconds := *source.RetryAfterSeconds
		out.RetryAfterSeconds = &seconds
	}
	return &out
}

// ValidateResult is the mandatory pre-emission policy boundary.
func ValidateResult(result CommandResult) error {
	if result == nil {
		return fmt.Errorf("output: nil command result")
	}
	env := result.envelope()
	if err := env.Validate(); err != nil {
		return err
	}
	if env.Outcome == OutcomePending {
		if env.Meta == nil || env.Meta.Operation == nil {
			return fmt.Errorf("output: pending result requires meta.operation")
		}
		op := env.Meta.Operation
		if strings.TrimSpace(op.ID) == "" {
			return fmt.Errorf("output: pending result requires operation.id")
		}
		if strings.TrimSpace(op.State) == "" {
			return fmt.Errorf("output: pending result requires operation.state")
		}
		if strings.TrimSpace(op.NextCommand) == "" {
			return fmt.Errorf("output: pending result requires operation.next_command")
		}
	}
	if env.Outcome == OutcomePartialFailure {
		if partial, ok := env.Data.(*PartialData); !ok || partial == nil {
			return fmt.Errorf("output: partial_failure result requires typed *PartialData")
		}
	}
	concrete, _ := result.(*commandResult)
	want := ExitCodeForEnvelope(env)
	if concrete == nil || !concrete.exitCodeOverride {
		if got := result.ExitCode(); got != want {
			return fmt.Errorf("output: result exit code=%d disagrees with outcome-derived code=%d", got, want)
		}
	} else if result.ExitCode() <= 0 {
		return fmt.Errorf("output: explicit compatibility exit code must be positive")
	}
	if env.Error != nil && env.Error.ExitCode != result.ExitCode() {
		return fmt.Errorf("output: error.exit_code=%d disagrees with process exit code=%d", env.Error.ExitCode, result.ExitCode())
	}
	return nil
}

// EnvelopeFromResult returns a detached envelope copy for adapters/tests.
func EnvelopeFromResult(result CommandResult) (*Envelope, error) {
	if err := ValidateResult(result); err != nil {
		return nil, err
	}
	return result.envelope(), nil
}

// 退出码表取值对齐：契约规范 §4 × 规划 v1.2 决策（OQ-1 已关闭——保留现行
// 码表 api=1 / auth=2 / validation=3 / PAT=4 / internal=5 / discovery=6，
// 仅新增 partial_failure 专用码 7；草案表中 validation→2 / confirmation→3
// 的拆分属 wire 破坏性重排，放弃）。confirmation_required 是 failure 的子类，
// 与 validation 共享 rc=3、以 subtype 区分（AC-13；runtime 同源于
// internal/errors 的 ExitCode 表）。
const (
	exitCodeOK         = 0
	exitCodeAPI        = 1
	exitCodeAuth       = 2
	exitCodeValidation = 3 // confirmation_required 子类共享此码（OQ-1 定案）
	exitCodePermission = 4 // PAT / permission failures
	exitCodeInternal   = 5
	exitCodeDiscovery  = 6
	exitCodePartial    = 7 // partial_failure 专用（契约 §4；规划 WS2 第4项；B142 将在 errors 侧补同源常量）
)

// subtypeConfirmationRequired 是门禁拦截的 failure 子类标记（契约规范 §2.4），
// 与 runtime apperrors.WithReason("confirmation_required") 形态同源。
const subtypeConfirmationRequired = "confirmation_required"

// ExitCodeForEnvelope 计算信封对应的进程退出码（B33，AC-10/I2；契约规范 §4）。
// 纯函数：只读信封字段、不做任何 I/O。映射规则：
//
//   - success / pending → 0（I2：exit 0 ⇔ ok；异步受理不是失败，§1/§4）；
//   - partial_failure → 7（部分成功专用码，区别于普通失败，§4）；
//   - failure → 按 Error.Type 类别映射，confirmation_required 子类恒 3；
//   - nil 信封 → 5（与 WriteEnvelopeTo 的 internal 类兜底信封同源）；
//   - 非法 outcome → 5（非法信封属框架缺陷，归 internal）。
//
// 判定只看 outcome / error 类别，不看可能被命令层篡改的 OK 字段（与 IsOK
// 同口径，I1）。退出码由 runner 出口统一决定、命令层禁止自行 os.Exit
// （§4 规则）；本函数为 Emitter 语义标注、runner 映射与测试提供同一依据。
func ExitCodeForEnvelope(env *Envelope) int {
	if env == nil {
		return exitCodeInternal
	}
	switch env.Outcome {
	case OutcomeSuccess, OutcomePending:
		return exitCodeOK
	case OutcomePartialFailure:
		return exitCodePartial
	case OutcomeFailure:
		return exitCodeForErrorInfo(env.Error)
	default:
		return exitCodeInternal
	}
}

// exitCodeForErrorInfo 把失败信封的 error 类别映射为退出码（契约规范 §4）。
// subtype=confirmation_required 优先于 type：门禁拦截无论挂在哪个 type 下
// 都恒为 3（AC-13）。error 缺席（违反 I3 的形态）按 internal 处理——
// 没有明细可分支的失败不得假装可恢复。未知 type 归 internal（不应发生）。
func exitCodeForErrorInfo(info *ErrorInfo) int {
	if info == nil {
		return exitCodeInternal
	}
	if info.Subtype == subtypeConfirmationRequired {
		return exitCodeValidation
	}
	switch info.Type {
	case "api":
		return exitCodeAPI
	case "auth":
		return exitCodeAuth
	case "validation":
		return exitCodeValidation
	case "permission":
		return exitCodePermission
	case "discovery":
		return exitCodeDiscovery
	default:
		return exitCodeInternal
	}
}

// toGeneric converts an arbitrary Go value into a generic JSON
// structure (map[string]any / []any / primitives) by round-tripping
// through JSON marshal/unmarshal. This ensures consistent types
// regardless of the original Go struct. The round-trip is always
// performed because even a map[string]any may contain typed values
// (e.g. []ir.CanonicalProduct) that gojq cannot handle.
func toGeneric(payload any) any {
	if payload == nil {
		return nil
	}
	data, err := marshalJSON(payload)
	if err != nil {
		return payload
	}
	var generic any
	if err := unmarshalJSONUseNumber(data, &generic); err != nil {
		return payload
	}
	return generic
}

var (
	marshalJSON       = json.Marshal
	unmarshalJSON     = json.Unmarshal
	marshalJSONOutput = jsonutil.Marshal
	marshalJSONIndent = jsonutil.MarshalIndent
)

func unmarshalJSONUseNumber(data []byte, out *any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(out); err != nil {
		return err
	}
	if _, err := decoder.Token(); err != io.EOF {
		if err == nil {
			return fmt.Errorf("unexpected trailing JSON value")
		}
		return err
	}
	*out = normalizeSafeJSONNumbers(*out)
	return nil
}

func normalizeSafeJSONNumbers(value any) any {
	switch typed := value.(type) {
	case json.Number:
		text := typed.String()
		if strings.ContainsAny(text, ".eE") {
			return typed
		}
		integer, err := strconv.ParseInt(text, 10, 64)
		if err == nil && integer >= -(1<<53) && integer <= 1<<53 {
			return float64(integer)
		}
		return typed
	case []any:
		for index := range typed {
			typed[index] = normalizeSafeJSONNumbers(typed[index])
		}
		return typed
	case map[string]any:
		for key := range typed {
			typed[key] = normalizeSafeJSONNumbers(typed[key])
		}
		return typed
	default:
		return value
	}
}

// WriteJSON marshals payload as indented JSON and writes it to w.
func WriteJSON(w io.Writer, payload any) error {
	data, err := marshalJSONIndent(payload, "", "  ")
	if err != nil {
		return apperrors.NewInternal("failed to encode command output as JSON")
	}
	_, err = fmt.Fprintln(w, string(data))
	return err
}
